import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { join } from 'node:path'

// Optional real-browser regression. Supply an installed Playwright module/channel
// through environment variables; no machine paths or browser profiles are committed.
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.MODEL_QA_PLAYWRIGHT || 'playwright')
const { expect } = require(`${process.env.MODEL_QA_PLAYWRIGHT || 'playwright'}/test`)
const base = process.env.MODEL_QA_BASE || 'http://127.0.0.1:4175/AI_Infra_Tutor_Page/'
const browser = await chromium.launch({ headless: true, ...(process.env.MODEL_QA_CHANNEL ? { channel: process.env.MODEL_QA_CHANNEL } : {}) })
let checks = 0
try {
  for (const width of [360, 390, 768, 1440]) {
    const page = await browser.newPage({ viewport: { width, height: 960 }, reducedMotion: 'reduce' })
    // This suite exercises the retained advanced tools. Compact defaults and
    // native disclosure interactions have their own workbench browser suite.
    const revealAdvanced = async () => {
      const match = new URL(page.url()).hash.match(/^#\/models\/([^/?]+)(?:\?|$)/)
      if (match && !['knowledge', 'compare', 'deepseek-v4-1-flash'].includes(match[1])) await expect(page.getByLabel('切换模型', { exact: true })).toHaveValue(match[1])
      await page.evaluate(() => {
      for (const id of ['model-full-diagram', 'model-cache-details', 'model-rank-details', 'model-native-details']) {
        const details = document.getElementById(id)
        if (details) details.open = true
      }
      })
    }
    const originalGoto = page.goto.bind(page), originalReload = page.reload.bind(page)
    page.goto = async (...args) => { const response = await originalGoto(...args); await revealAdvanced(); return response }
    page.reload = async (...args) => { const response = await originalReload(...args); await revealAdvanced(); return response }
    page.setDefaultTimeout(10000)
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.route('**/*', route => new URL(route.request().url()).origin === new URL(base).origin ? route.continue() : route.abort())
    async function fits(label) {
      const size = await page.evaluate(() => ({ viewport: innerWidth, content: document.documentElement.scrollWidth }))
      assert.ok(size.content <= size.viewport + 1, `${width}px ${label}: content width ${size.content}`)
      checks++
    }
    await page.goto(`${base}#/models/knowledge`, { waitUntil: 'networkidle' })
    await expect(page.getByRole('heading', { level: 1, name: '模型知识体系', exact: true })).toBeVisible()
    await expect(page.getByRole('region', { name: '知识层级', exact: true }).getByRole('link')).toHaveCount(9)
    await expect(page.getByRole('region', { name: '张量符号', exact: true }).locator('dt')).toHaveCount(8)
    await fits('knowledge system overview')
    if (process.env.MODEL_QA_SCREENSHOTS) await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `knowledge-overview-${width}.png`), animations: 'disabled' })
    for (const [id, title] of [['tensor-flow', '张量与数据流'], ['attention-state', 'Attention 与状态'], ['dense-moe', 'Dense 与 MoE'], ['parallelism', '并行策略'], ['precision', '精度与量化'], ['memory', '内存账本'], ['scheduling', '调度与请求生命周期'], ['kernels', 'Kernel 与执行图'], ['measurement', '性能指标与验证']]) {
      await page.goto(`${base}#/models/knowledge/${id}`, { waitUntil: 'networkidle' })
      await expect(page.getByRole('heading', { level: 1, name: title, exact: true })).toBeVisible()
      await expect(page.getByRole('article').getByRole('heading', { level: 2 })).toHaveCount(5)
      assert.doesNotMatch(await page.getByRole('article').innerText(), /？|先预测|本步答案/)
      await expect(page.getByRole('navigation', { name: '模型知识导航' }).getByRole('link', { name: '知识体系', exact: true })).toHaveAttribute('aria-current', 'page')
      await fits(`knowledge topic ${id}`)
    }
    if (width < 1024) await page.getByLabel('切换知识专题', { exact: true }).selectOption('parallelism')
    else await page.getByRole('navigation', { name: '知识专题', exact: true }).getByRole('link', { name: '并行策略', exact: true }).click()
    await expect(page).toHaveURL(/knowledge\/parallelism$/)
    await page.reload({ waitUntil: 'networkidle' })
    await expect(page.getByRole('heading', { level: 1, name: '并行策略', exact: true })).toBeVisible()
    if (process.env.MODEL_QA_SCREENSHOTS) await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `knowledge-topic-${width}.png`), animations: 'disabled' })
    await page.goto(`${base}#/models`, { waitUntil: 'networkidle' })
    await expect(page.locator('article[data-model-id]')).toHaveCount(19)
    const cardIds = () => page.locator('article[data-model-id]').evaluateAll(cards => cards.map(card => card.dataset.modelId))
    const downloadOrder = await cardIds()
    assert.equal(downloadOrder.length, 19)
    assert.deepEqual(downloadOrder.slice(0, 3), ['qwen3-8b', 'qwen3-5-9b', 'kimi-k3'])
    const firstDetails = page.locator('details[aria-label="Qwen3-8B 架构详情"]')
    await expect(firstDetails).not.toHaveAttribute('open', '')
    await firstDetails.locator('summary').focus()
    await page.keyboard.press('Enter')
    await expect(firstDetails).toHaveAttribute('open', '')
    await expect(firstDetails.getByRole('link', { name: '官方配置' })).toBeVisible()
    await page.keyboard.press('Enter')
    await expect(firstDetails).not.toHaveAttribute('open', '')
    await expect(page.getByRole('link', { name: 'DeepSeek-V3 近月下载来源', exact: true })).toHaveAttribute('href', 'https://huggingface.co/deepseek-ai/DeepSeek-V3-Base')
    await fits('compact popularity catalog')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await page.evaluate(() => window.scrollTo(0, 0))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `popularity-catalog-${width}.png`), animations: 'disabled' })
    }
    await page.getByRole('checkbox', { name: '对比 Kimi-K3', exact: true }).click()
    await expect(page.getByRole('checkbox', { name: '对比 Kimi-K3', exact: true })).toBeChecked()
    await page.getByLabel('模型排序', { exact: true }).selectOption('catalog')
    await expect.poll(async () => (await cardIds())[0]).toBe('glm-4-7-flash')
    await page.getByLabel('模型排序', { exact: true }).selectOption('name')
    await expect(page).toHaveURL(/sort=name/)
    await expect.poll(async () => (await cardIds())[0]).toBe('deepseek-v3')
    const nameOrder = await cardIds()
    assert.notDeepEqual(nameOrder, downloadOrder)
    await page.reload({ waitUntil: 'networkidle' })
    await expect.poll(cardIds).toEqual(nameOrder)
    await expect(page.getByRole('checkbox', { name: '对比 Kimi-K3', exact: true })).toBeChecked()
    await page.getByLabel('搜索模型', { exact: true }).fill('Qwen')
    await page.getByLabel('筛选 FFN 类型', { exact: true }).selectOption('moe')
    await expect(page.getByRole('article')).toHaveCount(2)
    await expect(page.getByRole('button', { name: '移除对比 Kimi-K3', exact: true })).toContainText('筛选外')
    const attentionSummary = page.locator('summary').filter({ hasText: '按注意力架构筛选' })
    await attentionSummary.focus()
    await page.keyboard.press('Enter')
    await page.getByRole('button', { name: /^DeltaNet 混合/ }).click()
    await expect(page).toHaveURL(/attention=hybrid/)
    await expect.poll(cardIds).toEqual(['qwen3-5-35b-a3b'])
    await page.reload({ waitUntil: 'networkidle' })
    await expect(attentionSummary.locator('..')).toHaveAttribute('open', '')
    await fits('expanded active architecture filter')
    await page.getByRole('button', { name: '清除筛选，保留选择', exact: true }).click()
    await expect(page.getByLabel('模型排序', { exact: true })).toHaveValue('name')
    await expect.poll(cardIds).toEqual(nameOrder)
    await expect(page.getByRole('checkbox', { name: '对比 Kimi-K3', exact: true })).toBeChecked()
    await page.getByLabel('模型排序', { exact: true }).selectOption('downloads')
    await expect(page).not.toHaveURL(/sort=/)
    await expect.poll(cardIds).toEqual(downloadOrder)
    await page.goto(`${base}#/models/kimi-k3?layer=11&node=moe&view=weights&b=2&s=4096&tp=4&ep=2&replicas=2&rank=3&wbits=4&precision=mixed&mlp=fp8&shared=bf16&experts=w4afp8`, { waitUntil: 'networkidle' })
    const picker = page.getByLabel('切换模型', { exact: true })
    await expect(picker.locator('option')).toHaveCount(18)
    const pickerIds = await picker.locator('option').evaluateAll(options => options.map(option => option.value))
    assert.deepEqual(pickerIds, downloadOrder.filter(id => id !== 'deepseek-v4-1-flash'))
    await picker.selectOption('glm-5-2')
    await expect(page).toHaveURL(/models\/glm-5-2\?/)
    await expect(page.locator('[aria-label="当前并行配置"]')).toContainText('模块混合精度')
    const switched = new URLSearchParams(new URL(page.url()).hash.split('?')[1])
    for (const [key, value] of Object.entries({ layer: '0', view: 'weights', b: '2', s: '4096', tp: '4', ep: '2', replicas: '2', rank: '3', wbits: '4', precision: 'mixed', mlp: 'fp8', shared: 'bf16', experts: 'w4afp8' })) assert.equal(switched.get(key), value, `${key} survives model switch`)
    await fits('compact model picker and preserved mixed precision')
    await page.goto(`${base}#/models/qwen3-8b?view=weights&node=ffn&tp=8&b=3&s=1024&replicas=2&rank=15&precision=mixed&mlp=fp8&experts=w4afp8&w4stage=processed`, { waitUntil: 'networkidle' })
    const qwenControls = page.getByRole('region', { name: '按模块选择精度', exact: true })
    await expect(qwenControls.getByRole('combobox')).toHaveCount(1)
    await expect(qwenControls.getByLabel('W4A8 权重阶段')).toHaveCount(0)
    const qwenFused = page.locator('[aria-label="Qwen3 Dense 融合布局"]')
    await qwenFused.locator('summary').click()
    await expect(qwenFused).toContainText('gate_up_proj [3072, 4096]')
    await expect(qwenFused).toContainText('Weight scale [24, 32] · FP32')
    await expect(qwenFused).toContainText('18,878,976 B')
    const qwenRank = page.getByRole('region', { name: '逐 rank 并行实验', exact: true })
    await expect(qwenRank).not.toContainText('Router FP32')
    await qwenRank.getByText('展开本模块内部张量', { exact: true }).click()
    await expect(qwenRank).toContainText('[3, 2 × 1536]')
    const qwenBoundary = qwenRank.getByLabel('模块边界逻辑载荷', { exact: true })
    await expect(qwenBoundary.getByLabel('模块输入', { exact: true })).toContainText('12,288 个逻辑元素')
    await expect(qwenBoundary.getByLabel('模块输出', { exact: true })).toContainText('24,576 B')
    await expect(qwenRank).toContainText('所列 Shape：9,216 个逻辑元素')
    await fits('Qwen dense-only FP8 and fused layout')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await qwenFused.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `qwen-dense-${width}.png`), animations: 'disabled' })
    }
    await qwenControls.getByLabel('Dense MLP 精度', { exact: true }).selectOption('bf16')
    await expect(page).toHaveURL(/mlp=bf16/)
    await expect(page).not.toHaveURL(/w4stage=/)
    await expect(qwenFused).toContainText('37,748,736 B')
    await expect(qwenFused).toContainText('Weight scale 无')
    await qwenRank.getByLabel('Rank 实验 TP', { exact: true }).press('Home')
    await expect(qwenFused).toContainText('gate_up_proj [24576, 4096]')
    await expect(qwenFused).toContainText('301,989,888 B')
    await expect(qwenBoundary.getByLabel('模块输入', { exact: true })).toContainText('24,576 B')
    await expect(qwenRank).toContainText('所列 Shape：73,728 个逻辑元素')
    await qwenControls.getByLabel('Dense MLP 精度', { exact: true }).selectOption('fp8')
    await expect(qwenFused).toContainText('151,031,808 B')
    await fits('Qwen BF16 to FP8 and TP1 reshard')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(qwenControls.getByLabel('Dense MLP 精度', { exact: true })).toHaveValue('fp8')
    await expect(qwenFused).toContainText('151,031,808 B')
    await fits('Qwen dense mixed URL reload')
    await expect(qwenBoundary.getByLabel('模块输出', { exact: true })).toContainText('24,576 B')
    await page.getByRole('button', { name: 'prefill', exact: true }).click()
    await expect(page).toHaveURL(/s=1024/)
    await expect(qwenBoundary.getByLabel('模块输入', { exact: true })).toContainText('12,582,912 个逻辑元素')
    await expect(qwenBoundary.getByLabel('模块输出', { exact: true })).toContainText('25,165,824 B')
    await fits('Qwen boundary payload follows Prefill independently of weight precision')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await qwenBoundary.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `rank-payload-${width}.png`), animations: 'disabled' })
    }
    await page.goto(`${base}#/models/kimi-k3?view=weights&node=attn-res-write&layer=0&tp=8&b=4`, { waitUntil: 'networkidle' })
    const stateBoundary = page.getByLabel('模块边界逻辑载荷', { exact: true })
    await expect(stateBoundary.getByLabel('模块输出', { exact: true })).toContainText('复合或动态 Shape：未推断元素量')
    await expect(stateBoundary.getByLabel('模块输出', { exact: true })).not.toContainText('2 B/元素参考')
    await fits('Kimi annotated bank does not fabricate an exact allocation')
    await page.goto(`${base}#/models/qwen3-30b-a3b?view=weights&node=moe&tp=8&ep=8&replicas=2&rank=15&precision=mixed&experts=w4afp8&w4stage=processed`, { waitUntil: 'networkidle' })
    const qMoE = page.getByRole('region', { name: '逐 rank 并行实验', exact: true })
    const qMoEControls = page.getByRole('region', { name: '按模块选择精度', exact: true })
    const qMoEFormat = qMoEControls.getByLabel('Routed MoE 精度', { exact: true })
    const qMoETotal = qMoE.getByLabel('当前模块权重小计', { exact: true })
    await expect(qMoEControls.getByRole('combobox')).toHaveCount(2)
    await expect(qMoETotal).toContainText('39,976,968 B')
    await expect(qMoEControls).toContainText('普通 Router 是 BF16')
    const qMoEOwnership = qMoE.getByLabel('专家归属与通信组', { exact: true })
    await qMoEOwnership.locator('summary').click()
    await expect(qMoEOwnership).toContainText('112–127（共 16 个）')
    await expect(qMoE).toContainText('gate/up：[T_e, 2 × 768]')
    await fits('Qwen MoE EP8 and scale-inclusive W4 post-load totals')
    await qMoE.getByLabel('Rank 实验 EP', { exact: true }).press('Home')
    await expect(qMoE.getByLabel('Rank 实验 EP', { exact: true })).toHaveAttribute('aria-valuetext', '1')
    await expect(qMoEFormat.locator('option[value="w4afp8"]')).toHaveCount(0)
    await expect(qMoEFormat).toHaveValue('bf16')
    await expect(page.getByRole('status').filter({ hasText: '128 对齐' })).toBeVisible()
    await expect(qMoETotal).toContainText('152,043,520 B')
    await qMoEFormat.selectOption('mxfp4')
    await expect(qMoEFormat).toHaveValue('mxfp4')
    await expect(qMoETotal).toContainText('41,156,608 B')
    await fits('Qwen MoE rejects unaligned W4 and keeps valid MXFP4 at MoE-TP8')
    await qMoE.getByLabel('Rank 实验 EP', { exact: true }).press('End')
    await expect(qMoEFormat.locator('option[value="w4afp8"]')).toHaveCount(1)
    await qMoEFormat.selectOption('w4afp8')
    await expect(qMoEFormat).toHaveValue('w4afp8')
    await expect(qMoETotal).toContainText('41,156,704 B')
    await qMoEControls.getByLabel('W4A8 权重阶段', { exact: true }).selectOption('processed')
    await expect(qMoETotal).toContainText('39,976,968 B')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(qMoETotal).toContainText('39,976,968 B')
    await expect(qMoE.getByRole('heading', { name: 'Rank 15 · DP 1 / TP local 7', exact: true })).toBeVisible()
    await fits('Qwen MoE precision slider recovers its range and reloads EP/DP/rank')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await qMoEControls.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `qwen-moe-${width}.png`), animations: 'disabled' })
    }
    await qMoE.getByLabel('Rank 实验模块', { exact: true }).selectOption('gqa')
    const headOwnership = qMoE.getByLabel('Attention head 归属', { exact: true })
    await expect(headOwnership).not.toHaveAttribute('open', '')
    await expect(headOwnership.locator('summary')).toContainText('Q heads 28–31 · K/V heads 3')
    await headOwnership.locator('summary').focus()
    await page.keyboard.press('Enter')
    await expect(headOwnership.getByRole('row')).toHaveCount(9)
    await expect(headOwnership.getByLabel('Attention Rank 15', { exact: true })).toHaveAttribute('aria-current', 'true')
    await expect(headOwnership.getByLabel('Attention Rank 15', { exact: true })).toContainText('R14 / R15')
    await expect(headOwnership).toContainText('[3584, 4096)')
    await expect(headOwnership).toContainText('[384, 512)')
    await fits('Qwen TP8 KV replicas and selected projection row intervals')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await headOwnership.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `attention-heads-${width}.png`), animations: 'disabled' })
    }
    await qMoE.getByRole('button', { name: '观察 Rank 14', exact: true }).click()
    await expect(headOwnership.locator('summary')).toContainText('Q heads 24–27 · K/V heads 3')
    await qMoE.getByLabel('观察 DP 副本', { exact: true }).selectOption('0')
    await expect(headOwnership.getByLabel('Attention Rank 6', { exact: true })).toHaveAttribute('aria-current', 'true')
    await expect(headOwnership.getByLabel('Attention Rank 6', { exact: true })).toContainText('R6 / R7')
    await expect(headOwnership.getByLabel('Attention Rank 14', { exact: true })).toHaveCount(0)
    await qMoE.getByLabel('Rank 实验 EP', { exact: true }).press('Home')
    await expect(qMoE.getByLabel('Rank 实验 EP', { exact: true })).toHaveAttribute('aria-valuetext', '1')
    await expect(headOwnership.locator('summary')).toContainText('Q heads 24–27 · K/V heads 3')
    await fits('DP changes replica identity and EP leaves attention heads unchanged')
    await qMoE.getByLabel('Rank 实验 TP', { exact: true }).press('Home')
    await expect(headOwnership.locator('summary')).toContainText('Q heads 0–31 · K/V heads 0–3')
    await expect(headOwnership.getByRole('row')).toHaveCount(2)
    await expect(headOwnership).toContainText('在当前 TP 组内不复制')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(headOwnership).not.toHaveAttribute('open', '')
    await expect(headOwnership.locator('summary')).toContainText('Q heads 0–31 · K/V heads 0–3')
    await fits('Attention head topology contracts with TP and restores from URL')
    await page.goto(`${base}#/models/glm-5-2?view=weights`, { waitUntil: 'networkidle' })
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await page.getByRole('region', { name: '模型与推理配置', exact: true }).evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `model-picker-${width}.png`), animations: 'disabled' })
    }
    await page.goto(`${base}#/models/compare?models=kimi-k3,deepseek-v4-1-flash`, { waitUntil: 'networkidle' })
    const comparePicker = page.getByRole('combobox', { name: '模型 1', exact: true })
    await expect(comparePicker.locator('option')).toHaveCount(19)
    assert.deepEqual(await comparePicker.locator('option').evaluateAll(options => options.map(option => option.value)), downloadOrder)
    await expect(comparePicker).toHaveValue('kimi-k3')
    await fits('popularity sorted comparison picker')
    await page.goto(`${base}#/models/deepseek-v4-flash?layer=2&node=csa&b=1&s=4096&tp=4`, { waitUntil: 'networkidle' })
    await page.locator('#model-node-csa').waitFor()
    await fits('diagram')
    await page.locator('summary').filter({ hasText: '模块知识卡' }).click()
    await expect(page.locator('#module-knowledge-content')).toBeVisible()
    await page.getByRole('button', { name: '下一模块', exact: true }).click()
    await page.locator('#module-knowledge-content').waitFor({ state: 'visible' })
    await expect(page).toHaveURL(/node=csa-cache/)
    await expect(page.locator('#module-knowledge-content')).toContainText('历史状态与上下文维度')
    await fits('expanded guide')
    await page.locator('summary').filter({ hasText: '模块知识卡' }).click()
    await page.locator('#model-node-hc-attn-pre').click()
    if (width < 1280) {
      await expect(page.getByRole('dialog', { name: '模块详情' })).toBeVisible()
      await fits('inspector dialog')
      await page.getByRole('button', { name: '关闭模块详情' }).click()
      await expect(page.locator('#model-node-hc-attn-pre')).toBeFocused()
    }
    await page.locator('#workspace-tab-cache').click()
    await page.locator('#workspace-panel-cache').waitFor({ state: 'visible' })
    const cache = page.getByRole('region', { name: '压缩注意力缓存实验' })
    await expect(cache).toContainText('43.89 MiB')
    await fits('cache')
    await page.getByRole('button', { name: 'prefill', exact: true }).click()
    await expect(cache.getByText('Prefill 最后 query 读取压缩条数', { exact: true })).toBeVisible()
    await page.getByLabel('每请求序列 token 数', { exact: true }).selectOption('2047')
    const history = cache.getByRole('heading', { name: '本层完整压缩历史', exact: true }).locator('..')
    await expect(history).toContainText('511 条')
    await page.getByLabel('每请求序列 token 数', { exact: true }).selectOption('2048')
    await expect(history).toContainText('512 条')
    await page.getByLabel('KV 缓存精度', { exact: true }).selectOption('1')
    await expect(page).toHaveURL(/bytes=1/)
    await page.getByRole('button', { name: 'TP 8', exact: true }).click()
    await expect(page.getByRole('button', { name: 'TP 8', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page).toHaveURL(/tp=8/)
    await page.locator('#workspace-tab-cache').focus()
    await page.keyboard.press('ArrowRight')
    await expect(page.locator('#workspace-panel-weights')).toBeVisible()
    await expect(page).toHaveURL(/view=weights/)
    await fits('weights')
    await page.keyboard.press('Home')
    await expect(page.locator('#workspace-panel-diagram')).toBeVisible()
    await page.getByText('展开完整层分布', { exact: true }).click()
    await page.getByRole('button', { name: 'Layer 3 · SWA + HCA · MoE', exact: true }).click()
    await expect(page.locator('#model-node-hca')).toBeVisible()
    await expect(page.locator('#model-node-csa')).toHaveCount(0)
    await expect(page).toHaveURL(/layer=3/)
    const restored = new URLSearchParams(new URL(page.url()).hash.split('?')[1])
    for (const [key, value] of Object.entries({ phase: 'prefill', tp: '8', b: '1', s: '2048', bytes: '1' })) assert.equal(restored.get(key), value, `${key} survives workspace and layer changes`)
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await page.locator('[aria-label="mHC Attention 子层"]').screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `mhc-${width}.png`) })
      await page.locator('#workspace-tab-cache').click()
      await cache.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `cache-${width}.png`) })
    }
    await page.goto(`${base}#/models/glm-5-3-flash?layer=3&node=mla&view=cache&phase=prefill&b=1&s=4095&tp=4`, { waitUntil: 'networkidle' })
    const glmCache = page.getByRole('region', { name: 'KDA 与池化 DSA 缓存实验' })
    await expect(glmCache).toContainText('2,051 个有效读取位置')
    await expect(glmCache).toContainText('再加 3 个尾部 token')
    await fits('GLM pooled-index cache')
    await page.getByLabel('每请求序列 token 数', { exact: true }).selectOption('4096')
    await expect(glmCache).toContainText('2,048 个有效读取位置')
    await expect(glmCache).toContainText('81.97 MiB')
    await page.locator('#workspace-tab-diagram').click()
    await page.locator('#model-node-hc-expand').click()
    if (width < 1280) {
      await expect(page.getByRole('dialog', { name: '模块详情' })).toBeVisible()
      await expect(page.getByRole('dialog', { name: '模块详情' })).toContainText('替换')
      await page.getByRole('button', { name: '关闭模块详情' }).click()
      await expect(page.locator('#model-node-hc-expand')).toBeFocused()
    }
    const layerSlider = page.getByLabel('查看 Decoder 层号', { exact: true })
    await layerSlider.focus()
    if (width < 1280) {
      // Reproduce a close notification arriving after the user moves elsewhere.
      await page.getByRole('dialog', { name: '模块详情', includeHidden: true }).evaluate(el => el.dispatchEvent(new Event('close')))
    }
    await expect(layerSlider).toBeFocused()
    await page.keyboard.press('Home')
    await expect(page.locator('#model-node-kda')).toBeVisible()
    await expect(page.locator('#model-node-dense-ffn')).toBeVisible()
    await expect(page.locator('[aria-label="mHC Dense FFN 子层"]')).toBeVisible()
    const order = await page.locator('[id^="model-node-"]').evaluateAll(nodes => nodes.map(n => n.id))
    assert.deepEqual(order.slice(0, 4), ['model-node-embedding', 'model-node-vision', 'model-node-hc-expand', 'model-node-hc-attn-pre'])
    await fits('GLM multimodal diagram')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await page.locator('[aria-label="mHC Attention 子层"]').screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `glm-kda-${width}.png`) })
      await page.locator('#workspace-tab-cache').click()
      await glmCache.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `glm-cache-${width}.png`) })
    }
    await page.goto(`${base}#/models/kimi-k3?layer=11&node=attn-res-read&phase=prefill&b=1&s=4096&tp=4`, { waitUntil: 'networkidle' })
    const depth = page.getByRole('region', { name: 'Attention Residual 深度实验' })
    await expect(depth).toContainText('1 个快照')
    await expect(depth).toContainText('448 MiB')
    await depth.getByRole('button', { name: '观察 Layer 12', exact: true }).click()
    await expect(page).toHaveURL(/layer=12/)
    await expect(depth).toContainText('快照槽位 1')
    await expect(depth).toContainText('FFN 再从 3 个候选聚合')
    await expect(page.locator('#model-node-attn-res-write')).toContainText('重置块内累加状态')
    await depth.getByText('本层 FFN 可读快照', { exact: true }).click()
    await expect(depth).toContainText('Layers 0–11 的子层输出和')
    await depth.getByRole('button', { name: '观察 Layer 13', exact: true }).click()
    await expect(depth).toContainText('2 个快照')
    await expect(page.locator('#model-node-attn-res-write')).toContainText('不写入')
    await fits('Kimi depth boundary')
    await page.locator('#model-node-attn-res-read').click()
    if (width < 1280) {
      await expect(page.getByRole('dialog', { name: '模块详情' })).toContainText('不回写旧快照')
      await page.getByRole('button', { name: '关闭模块详情' }).click()
      await expect(page.locator('#model-node-attn-res-read')).toBeFocused()
    }
    await page.getByRole('button', { name: 'decode', exact: true }).click()
    await expect(depth).toContainText('112 KiB')
    await depth.getByRole('button', { name: '观察 Layer 92', exact: true }).click()
    await expect(page.locator('#model-node-mla')).toBeVisible()
    await expect(page.locator('#model-node-kda')).toHaveCount(0)
    await expect(depth).toContainText('FFN 再从 9 个候选聚合')
    const moeFlow = page.getByLabel('LatentMoE 支路图', { exact: true })
    await moeFlow.getByText('展开 routed / shared 数据流', { exact: true }).click()
    await expect(moeFlow.getByRole('region', { name: 'Routed latent 支路' })).toContainText('7168 → 3584')
    await expect(moeFlow.getByRole('region', { name: 'Shared 主干支路' })).toContainText('7168 → 6144 → 7168')
    await fits('Kimi latent MoE branches')
    await moeFlow.getByText('展开 routed / shared 数据流', { exact: true }).click()
    if (process.env.MODEL_QA_SCREENSHOTS) await depth.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `kimi-depth-${width}.png`) })
    await page.locator('#workspace-tab-cache').click()
    const kimiCache = page.getByRole('region', { name: 'KDA 与 Gated MLA 缓存实验' })
    await expect(kimiCache).toContainText('215.14 MiB')
    await page.getByLabel('KV 缓存精度', { exact: true }).selectOption('1')
    await expect(kimiCache).toContainText('161.14 MiB')
    await page.getByRole('button', { name: 'TP 8', exact: true }).click()
    await expect(kimiCache).toContainText('107.57 MiB')
    await fits('Kimi cache')
    if (process.env.MODEL_QA_SCREENSHOTS) await kimiCache.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `kimi-cache-${width}.png`) })
    const kimiRestored = new URLSearchParams(new URL(page.url()).hash.split('?')[1])
    for (const [key, value] of Object.entries({ layer: '92', phase: 'decode', tp: '8', b: '1', s: '4096', bytes: '1', view: 'cache' })) assert.equal(kimiRestored.get(key), value)
    await page.goto(`${base}#/models/llama-3-1-8b?layer=0&node=gqa&view=weights&phase=decode&b=2&s=4096&tp=4&replicas=2&rank=7`, { waitUntil: 'networkidle' })
    const rankLab = page.getByRole('region', { name: '逐 rank 并行实验' })
    await expect(rankLab.getByRole('heading', { name: 'Rank 7 · DP 1 / TP local 3', exact: true })).toBeVisible()
    await expect(rankLab).toContainText('2 副本 × TP 4 = 8 张卡；4 个不同请求')
    await expect(rankLab).toContainText('[2, 4096]')
    const qDetails = rankLab.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^q_proj · TP local/ }) })
    await rankLab.getByText('q_proj · TP local · 8 MiB', { exact: true }).click()
    await expect(qDetails.getByText('[8 × 128, 4096]', { exact: true })).toBeVisible()
    await fits('rank module detail')
    await page.getByLabel('独立 DP 副本数', { exact: true }).press('End')
    await rankLab.getByLabel('观察 DP 副本', { exact: true }).selectOption('7')
    await rankLab.getByRole('button', { name: '观察 Rank 31', exact: true }).click()
    await expect(page).toHaveURL(/rank=31/)
    await page.getByLabel('Rank 实验 TP', { exact: true }).press('Home')
    await expect(rankLab.getByRole('heading', { name: 'Rank 7 · DP 7 / TP local 0', exact: true })).toBeVisible()
    await page.getByLabel('独立 DP 副本数', { exact: true }).press('Home')
    await expect(rankLab.getByRole('heading', { name: 'Rank 0 · DP 0 / TP local 0', exact: true })).toBeVisible()
    await page.getByLabel('Rank 实验权重位宽', { exact: true }).press('Home')
    await expect(page).toHaveURL(/wbits=4/)
    await expect(qDetails.getByText('[32 × 128, 4096]', { exact: true })).toHaveCount(2)
    await page.getByRole('button', { name: 'prefill', exact: true }).click()
    await expect(rankLab).toContainText('[8192, 4096]')
    const rankUrl = page.url()
    await page.reload({ waitUntil: 'networkidle' })
    await expect(page).toHaveURL(rankUrl)
    await expect(rankLab).toContainText('统一假定位宽：4-bit')
    await fits('rank reload and sliders')
    if (process.env.MODEL_QA_SCREENSHOTS) await rankLab.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `rank-${width}.png`) })
    await page.goto(`${base}#/models/kimi-k3?layer=92&node=moe&view=weights&phase=decode&b=2&s=4096&tp=8&rank=7`, { waitUntil: 'networkidle' })
    const epLab = page.getByRole('region', { name: '逐 rank 并行实验' })
    await page.getByLabel('Rank 实验 EP', { exact: true }).press('End')
    await expect(page).toHaveURL(/ep=8/)
    const ownership = epLab.locator('[aria-label="专家归属与通信组"]')
    await ownership.locator('summary').click()
    await expect(ownership).toContainText('EP rank 7 · MoE-TP rank 0 / 1')
    await expect(ownership).toContainText('784–895（共 112 个）')
    const expertWeight = epLab.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^experts.gate_up_proj/ }) })
    await expertWeight.locator('summary').click()
    await expect(expertWeight).toContainText('[112, 2 × 3072, 3584]')
    await expect(epLab.locator('[aria-label="本地专家激活 Shape"]')).toContainText('[T_e, 3584]')
    await fits('EP full expert and latent shapes')
    await page.getByLabel('Rank 实验 EP', { exact: true }).press('ArrowLeft')
    await expect(ownership).toContainText('EP rank 3 · MoE-TP rank 1 / 2')
    await expect(ownership).toContainText('672–895（共 224 个）')
    await expect(ownership).toContainText('分片组：R6 / R7')
    await expect(expertWeight).toContainText('[224, 2 × 1536, 3584]')
    const epLedger = page.getByRole('region', { name: 'Decoder 权重账本', exact: true })
    await expect(page.getByLabel('Expert EP', { exact: true })).toHaveValue('4')
    const moeRow = epLedger.locator('[data-weight-module="moe"]')
    await moeRow.locator(':scope > summary').click()
    await expect(moeRow).toContainText('[224, 2 × 1536, 3584]')
    await page.getByRole('tab', { name: '结构图', exact: true }).click()
    await page.getByRole('region', { name: '模型核心结构', exact: true }).getByRole('button').filter({ hasText: 'LatentMoE' }).click()
    const epInspector = page.getByRole('dialog', { name: '模块详情' })
    await expect(epInspector).toContainText('[224, 2 × 1536, 3584]')
    await expect(epInspector).not.toContainText('[896, 2 × 384, 3584]')
    const inspectedExpertShape = epInspector.getByText('[224, 2 × 1536, 3584]', { exact: true })
    await inspectedExpertShape.scrollIntoViewIfNeeded()
    await expect(inspectedExpertShape).toBeInViewport({ ratio: 1 })
    if (process.env.MODEL_QA_SCREENSHOTS) await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `ep-shared-inspector-${width}.png`) })
    await page.getByRole('button', { name: '关闭模块详情', exact: true }).click()
    await page.getByRole('tab', { name: '缓存容量', exact: true }).click()
    await expect(page.getByRole('tabpanel', { name: '缓存容量', exact: true })).toContainText('基础缓存口径：TP 8')
    await page.getByRole('tab', { name: '权重清单', exact: true }).click()
    await fits('EP shared across diagram ledger and cache')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(page.getByLabel('Rank 实验 EP', { exact: true })).toHaveAttribute('aria-valuetext', '4')
    await fits('hybrid EP and MoE-TP reload')
    if (process.env.MODEL_QA_SCREENSHOTS) await ownership.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `ep-groups-${width}.png`) })
    await page.getByLabel('Rank 实验 TP', { exact: true }).press('Home')
    await expect(page.getByLabel('Rank 实验 EP', { exact: true })).toBeDisabled()
    await expect(page.getByLabel('Rank 实验 EP', { exact: true })).toHaveAttribute('aria-valuetext', '1')
    await expect(ownership).toContainText('0–895（共 896 个）')
    await page.goto(`${base}#/models/deepseek-v4-1-flash?layer=24&world=4&rank=3`, { waitUntil: 'networkidle' })
    const v41Sources = page.getByRole('region', { name: 'CSA2 跨层来源' })
    const v41Cache = page.getByRole('region', { name: 'V4.1 缓存格式实验' })
    await expect(v41Sources.getByRole('heading', { name: 'Layer 24 · Decoder 20–39 · Reindex', exact: true })).toBeVisible()
    await expect(page.getByRole('tabpanel')).toHaveCount(1)
    await page.getByRole('tab', { name: '缓存容量', exact: true }).click()
    await expect(v41Cache).toContainText('17.52 MiB')
    await page.getByLabel('V4.1 缓存口径', { exact: true }).selectOption('packed')
    await expect(v41Cache).toContainText('6.08 MiB')
    await v41Cache.getByRole('button', { name: '定位 Owner Layer 20', exact: true }).click()
    await expect(v41Sources).toBeFocused()
    await expect(page.getByRole('tab', { name: '结构图', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page).toHaveURL(/storage=packed/)
    await page.getByRole('button', { name: '跳转主 KV来源 Layer 20', exact: true }).click()
    await expect(v41Sources.getByRole('heading', { name: 'Layer 20 · Decoder 20–39 · Full', exact: true })).toBeVisible()
    await page.getByLabel('V4.1 序列长度', { exact: true }).selectOption('16385')
    await expect(v41Sources).toContainText('2,049 个可见')
    await expect(v41Sources).toContainText('钉住最新块 2048')
    await fits('V4.1 candidate and source state')
    await page.getByLabel('V4.1 world', { exact: true }).press('End')
    const v41Rank = page.getByLabel('V4.1 rank', { exact: true })
    await expect(v41Rank).toHaveAttribute('max', '7')
    await v41Rank.press('End')
    await expect(v41Rank).toHaveValue('7')
    await expect(page).toHaveURL(/rank=7(?:&|$)/)
    await page.getByRole('button', { name: '观察 V4.1 Layer 14', exact: true }).click()
    const v41Flow = page.getByRole('region', { name: 'V4.1 单层数据流' })
    await expect(v41Flow).toContainText('首先注入 Engram')
    await expect(v41Flow).toContainText('本 rank 持有专家 336–383')
    await page.getByRole('button', { name: '保留条件查看逐 rank 张量', exact: true }).click()
    await expect(page.getByRole('region', { name: 'V4.1 逐 rank 张量流', exact: true })).toBeFocused()
    const engramWeight = page.getByRole('region', { name: 'V4.1 参考权重布局' }).locator('details').filter({ has: page.locator('summary').filter({ hasText: /^engram.embed/ }) })
    await engramWeight.locator('summary').click()
    await expect(engramWeight).toContainText('[48002086, 256]')
    await expect(engramWeight).toContainText('[48002086, 8]')
    await fits('V4.1 Engram weight packing')
    await page.getByLabel('V4.1 权重格式', { exact: true }).selectOption('4')
    await expect(engramWeight).toContainText('4-bit 理论载荷')
    await expect(engramWeight).not.toContainText('E8M0')
    const v41TensorFlow = page.getByRole('region', { name: 'V4.1 逐 rank 张量流', exact: true })
    await page.getByLabel('V4.1 张量流支路', { exact: true }).selectOption('engram')
    await expect(v41TensorFlow).toContainText('padding 6 行')
    await v41TensorFlow.getByRole('button', { name: 'Rank 0', exact: true }).click()
    await expect(v41Rank).toHaveValue('0')
    await expect(v41TensorFlow).toContainText('padding 0 行')
    await page.getByLabel('V4.1 独立副本', { exact: true }).press('End')
    await expect(v41Rank).toHaveAttribute('max', '63')
    await v41Rank.press('End')
    await expect(v41Rank).toHaveValue('63')
    await expect(v41TensorFlow).toContainText('副本 7 内归约组：[56, 57, 58, 59, 60, 61, 62, 63]')
    await expect(v41TensorFlow).toContainText('padding 6 行')
    await page.getByLabel('V4.1 张量流支路', { exact: true }).selectOption('moe')
    await expect(v41TensorFlow).toContainText('[T_e, 2304]')
    await page.getByLabel('V4.1 阶段', { exact: true }).selectOption('prefill')
    await expect(v41TensorFlow).toContainText('N = 16,385')
    await fits('V4.1 per-rank tensor flow')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await v41TensorFlow.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `v41-rank-flow-${width}.png`) })
    }
    await page.getByLabel('V4.1 独立副本', { exact: true }).press('Home')
    await expect(v41Rank).toHaveValue('7')
    await page.getByRole('button', { name: '返回当前层结构与残差流', exact: true }).click()
    await page.getByRole('button', { name: '观察 V4.1 Layer 0', exact: true }).click()
    await expect(v41Flow).toContainText('初始 one-hot [1,0,0,0]')
    await page.getByLabel('V4.1 world', { exact: true }).press('Home')
    await expect(page.getByLabel('V4.1 rank', { exact: true })).toHaveValue('0')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(page.getByLabel('V4.1 缓存口径', { exact: true })).toHaveValue('packed')
    await expect(page.getByLabel('V4.1 权重格式', { exact: true })).toHaveValue('4')
    await expect(page.getByLabel('V4.1 张量流支路', { exact: true })).toHaveValue('moe')
    await fits('V4.1 reference reload')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await v41Sources.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `v41-sources-${width}.png`) })
    }
    await page.getByRole('button', { name: '展开专题', exact: true }).click()
    const guide = page.getByRole('region', { name: 'V4.1 专题索引', exact: true })
    const lessonViews = ['结构图', '结构图', '结构图', '权重清单', '权重清单', '权重清单', '缓存容量', '权重清单']
    for (let step = 0; step < 8; step++) {
      if (step) await guide.getByLabel('V4.1 架构专题', { exact: true }).selectOption(String(step))
      await expect(page.getByRole('tab', { name: lessonViews[step], exact: true })).toHaveAttribute('aria-selected', 'true')
      await expect(page.locator('#v41-topic-content')).toBeVisible()
      await expect(page).toHaveURL(new RegExp(`lesson=${step}(?:&|$)`))
      await expect(page).toHaveURL(/storage=packed/)
      await expect(page).toHaveURL(/weights=4/)
      await expect(page).toHaveURL(/s=16385/)
    }
    await guide.getByLabel('V4.1 架构专题', { exact: true }).selectOption('5')
    await expect(page.locator('#v41-topic-content')).toBeVisible()
    await page.getByLabel('V4.1 world', { exact: true }).press('End')
    await expect(page.getByLabel('V4.1 world', { exact: true })).toHaveValue('3')
    await expect(page.getByLabel('V4.1 rank', { exact: true })).toHaveAttribute('max', '7')
    await page.getByLabel('V4.1 rank', { exact: true }).press('End')
    await expect(page.getByLabel('V4.1 rank', { exact: true })).toHaveValue('7')
    await expect(page.locator('#v41-topic-content')).toContainText('6 行 padding')
    await fits('V4.1 direct topic content')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await guide.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `v41-guide-${width}.png`), animations: 'disabled' })
    }
    await guide.getByRole('button', { name: '定位对应模块', exact: true }).click()
    await expect(v41TensorFlow).toBeFocused()
    await expect(v41TensorFlow).toContainText('padding 6 行')
    await page.getByRole('tab', { name: '权重清单', exact: true }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(page.getByRole('tabpanel', { name: '缓存容量', exact: true })).toBeVisible()
    await expect(page.getByRole('tab', { name: '缓存容量', exact: true })).toBeFocused()
    await page.reload({ waitUntil: 'networkidle' })
    await expect(page.getByRole('tabpanel', { name: '缓存容量', exact: true })).toBeVisible()
    await expect(page.locator('#v41-topic-content')).toBeVisible()
    await expect(page.getByLabel('V4.1 rank', { exact: true })).toHaveValue('7')
    await expect(page).toHaveURL(/lesson=5/)
    await fits('V4.1 workspace keyboard and lesson URL reload')
    await page.goto(`${base}#/models?q=Engram&attention=compressed&ffn=moe`, { waitUntil: 'networkidle' })
    await expect(page.getByRole('article')).toHaveCount(1)
    await page.getByRole('checkbox', { name: '对比 DeepSeek-V4.1-Flash', exact: true }).click()
    await expect(page.getByRole('checkbox', { name: '对比 DeepSeek-V4.1-Flash', exact: true })).toBeChecked()
    await page.getByLabel('搜索模型', { exact: true }).fill('V4')
    await page.getByRole('checkbox', { name: '对比 DeepSeek-V4-Flash', exact: true }).click()
    await expect(page.getByRole('checkbox', { name: '对比 DeepSeek-V4-Flash', exact: true })).toBeChecked()
    await fits('V4.1 unified searchable directory')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await page.getByRole('region', { name: '模型目录结果', exact: true }).evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `v41-directory-${width}.png`), animations: 'disabled' })
    }
    await page.getByRole('link', { name: '比较已选模型', exact: true }).click()
    await page.getByLabel('并发请求 B', { exact: true }).selectOption('1')
    await expect(page).toHaveURL(/b=1(?:&|$)/)
    await page.getByLabel('每请求序列 S', { exact: true }).selectOption('4096')
    const v41Compare = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'DeepSeek-V4.1-Flash', exact: true }) })
    await expect(v41Compare.locator('output')).toHaveText('17.52 MiB')
    await page.getByLabel('对比 KV 精度', { exact: true }).selectOption('1')
    await expect(v41Compare.locator('output')).toHaveText('17.52 MiB')
    await expect(v41Compare).toContainText('参考 BF16 buffer')
    await page.getByLabel('对比 V4.1 存储口径', { exact: true }).selectOption('packed')
    await expect(v41Compare.locator('output')).toHaveText('6.08 MiB')
    await page.getByLabel('容量视图', { exact: true }).selectOption('group')
    await expect(page).toHaveURL(/view=group/)
    await page.getByLabel('对比 Tensor Parallel', { exact: true }).selectOption('8')
    await expect(v41Compare.locator('output')).toHaveText('48.63 MiB')
    await fits('V4.1 independently labeled cache formats')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await page.getByRole('region', { name: '当前条件下的模型缓存', exact: true }).evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `v41-compare-${width}.png`), animations: 'disabled' })
    }
    await page.reload({ waitUntil: 'networkidle' })
    await expect(page.getByLabel('对比 V4.1 存储口径', { exact: true })).toHaveValue('packed')
    await expect(v41Compare.locator('output')).toHaveText('48.63 MiB')
    await v41Compare.getByRole('link', { name: '携带条件查看 V4.1 缓存', exact: true }).click()
    await expect(page.getByRole('tabpanel', { name: '缓存容量', exact: true })).toBeVisible()
    await expect(page.getByLabel('V4.1 world', { exact: true })).toHaveValue('3')
    await expect(page.getByLabel('V4.1 序列长度', { exact: true })).toHaveValue('4096')
    await expect(page.getByLabel('V4.1 缓存口径', { exact: true })).toHaveValue('packed')
    await expect(page.getByRole('region', { name: 'V4.1 缓存格式实验', exact: true })).toContainText('每 rank 已占用记录与增量状态：6.08 MiB')
    await page.getByRole('link', { name: '携带 B / S / world 对照 V4 缓存（单副本）', exact: true }).click()
    await expect(page.getByLabel('对比 V4.1 存储口径', { exact: true })).toHaveValue('packed')
    await expect(page.getByLabel('对比 Tensor Parallel', { exact: true })).toHaveValue('8')
    await expect(page.getByLabel('并发请求 B', { exact: true })).toHaveValue('1')
    await fits('V4.1 comparison and explorer bidirectional handoff')
    await page.goto(`${base}#/models/glm-5-2/dpa?tp=8&dp=4&ep=4&rank=5&groups=3,1,0,2`, { waitUntil: 'networkidle' })
    const dpaFlow = page.getByRole('region', { name: 'DPA rank 数据流', exact: true })
    const dpaMemory = page.getByRole('region', { name: 'DPA padding 与缓存', exact: true })
    await expect(dpaFlow).toContainText('Rank 5 · DPA 2 / Attention TP rank 1')
    await expect(dpaFlow).toContainText('Attention peers：R4 / R5')
    await expect(dpaFlow).toContainText('[0, 6144]')
    await expect(dpaMemory).toContainText('padding 10')
    await expect(dpaMemory).toContainText('本基线选择 MAX_LEN')
    await fits('DPA idle rank and MAX_LEN')
    const dpaMap = page.getByRole('region', { name: 'DPA 缓冲区分段图', exact: true })
    await expect(dpaMap).toContainText('有效 1 · 对齐补齐 1 · MAX 补齐 2')
    await expect(dpaMap).toContainText('有效返回 [12, 14)')
    await dpaMap.getByRole('button', { name: '查看 DPA 缓冲组 0', exact: true }).click()
    await expect(dpaFlow).toContainText('Rank 1 · DPA 0 / Attention TP rank 1')
    await expect(dpaMap).toContainText('返回当前组仅取 [0, 3)')
    await dpaMap.getByRole('button', { name: '查看 DPA 缓冲组 2', exact: true }).focus()
    await page.keyboard.press('Enter')
    await expect(dpaFlow).toContainText('Rank 5 · DPA 2 / Attention TP rank 1')
    await expect(dpaMap.getByRole('button', { name: '查看 DPA 缓冲组 2', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page).toHaveURL(/groups=3%2C1%2C0%2C2/)
    await fits('DPA buffer map keyboard group selection')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await dpaMap.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `dpa-buffer-${width}.png`), animations: 'disabled' })
    }
    const dpaWeights = page.getByRole('region', { name: 'DPA 本层权重', exact: true })
    const dpaQ = dpaWeights.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^q_b_proj/ }) })
    await dpaQ.locator('summary').click()
    await expect(dpaQ).toContainText('[32 × 256, 2048]')
    await page.getByLabel('DPA ep', { exact: true }).press('End')
    await expect(dpaFlow).toContainText('本地专家 160–191')
    const dpaExpert = dpaWeights.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^experts.gate_up_proj/ }) })
    await dpaExpert.locator('summary').click()
    await expect(dpaExpert).toContainText('[32, 2 × 2048, 6144]')
    await expect(dpaQ).toContainText('[32 × 256, 2048]')
    await page.getByLabel('DPA 阶段', { exact: true }).selectOption('prefill')
    await expect(dpaMemory).toContainText('本基线选择 SUM_LEN')
    await expect(dpaMemory).toContainText('24,576（padding 0）')
    await page.getByRole('button', { name: 'DPA 观察 Rank 0', exact: true }).click()
    await expect(dpaFlow).toContainText('[12288, 6144]')
    await page.getByLabel('DPA 组 0 请求数', { exact: true }).press('Home')
    await expect(dpaFlow).toContainText('[0, 6144]')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(page.getByLabel('DPA 组 0 请求数', { exact: true })).toHaveValue('0')
    await expect(page.getByLabel('DPA ep', { exact: true })).toHaveAttribute('aria-valuetext', '8')
    await fits('DPA unequal Prefill and reload')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await dpaFlow.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `dpa-flow-${width}.png`) })
    }
    await page.getByLabel('DPA tp', { exact: true }).press('Home')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('aria-valuetext', '1')
    await expect(page.getByLabel('DPA ep', { exact: true })).toHaveAttribute('aria-valuetext', '1')
    await expect(page.getByRole('region', { name: 'DPA 请求分组', exact: true }).getByRole('slider')).toHaveCount(1)
    await expect(dpaFlow).toContainText('全部组空闲')
    await expect(dpaMap).toContainText('空缓冲：所有组都没有有效 token')
    await page.getByLabel('DPA layer', { exact: true }).press('Home')
    await expect(dpaFlow).toContainText('当前 Dense 层不执行 routed 专家')
    await fits('DPA topology contraction and Dense layer')
    await page.goto(`${base}#/models/glm-5-2/dpa?tp=8&dp=4&ep=4&rank=5&groups=3,1,0,2&bits=4`, { waitUntil: 'networkidle' })
    const dpaPrecision = page.getByRole('region', { name: '按模块选择精度', exact: true })
    await dpaPrecision.getByRole('button', { name: '按模块混合精度', exact: true }).click()
    await expect(page.getByLabel('DPA 权重位宽', { exact: true })).toHaveCount(0)
    await dpaPrecision.getByLabel('Routed MoE 精度', { exact: true }).selectOption('w4afp8')
    await expect(page).toHaveURL(/experts=w4afp8/)
    await dpaExpert.locator('summary').click()
    await expect(dpaExpert).toContainText('Payload Shape [64, 2048, 3072]')
    await expect(dpaExpert).toContainText('Weight scale [64, 2048, 48] · FP32')
    await expect(dpaExpert).toContainText('Input scale [64, 2] · BF16 · 256 B')
    const dpaRouter = dpaWeights.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^gate.weight/ }) })
    await dpaRouter.locator('summary').click()
    await expect(dpaRouter).toContainText('FP32 · router')
    const dpaTotals = page.getByLabel('DPA Decoder 权重汇总', { exact: true })
    const dpaAllLayerTotal = dpaTotals.locator('output').nth(1)
    const beforeDensePrecision = await dpaAllLayerTotal.innerText()
    const beforeCurrent = await dpaTotals.locator('output').first().innerText()
    await dpaPrecision.getByLabel('Dense MLP 精度', { exact: true }).selectOption('fp8')
    await expect(dpaAllLayerTotal).not.toHaveText(beforeDensePrecision)
    await expect(dpaTotals.locator('output').first()).toHaveText(beforeCurrent)
    const boundary = page.getByLabel('DPA 边界张量载荷', { exact: true })
    await boundary.locator('summary').focus()
    await page.keyboard.press('Enter')
    await expect(boundary.locator('[data-tensor-id="attention-input"]')).toContainText('[0, 6144] · BF16')
    await expect(boundary.locator('[data-tensor-id="attention-input"]')).toContainText('0 B')
    await expect(boundary.locator('[data-tensor-id="ffn-input"]')).toContainText('196,608 B')
    await fits('DPA mixed weights and idle boundary bytes')
    const beforeDpa = await dpaAllLayerTotal.innerText()
    await page.getByLabel('DPA dp', { exact: true }).press('Home')
    await expect(dpaAllLayerTotal).not.toHaveText(beforeDpa)
    await expect(dpaExpert).toContainText('Payload Shape [64, 2048, 3072]')
    await expect(boundary.locator('[data-tensor-id="attention-input"]')).toContainText('[3, 6144] · BF16')
    await expect(boundary.locator('[data-tensor-id="ffn-input"]')).toContainText('36,864 B')
    await page.getByLabel('DPA dp', { exact: true }).press('ArrowRight')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('aria-valuetext', '2')
    await page.getByLabel('DPA dp', { exact: true }).press('ArrowRight')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('aria-valuetext', '4')
    await page.getByLabel('DPA ep', { exact: true }).press('End')
    await expect(dpaExpert).toContainText('Payload Shape [32, 4096, 3072]')
    await expect(dpaExpert).toContainText('Input scale [32, 2] · BF16 · 128 B')
    const dpaBeforeLayer = await dpaAllLayerTotal.innerText()
    await page.getByLabel('DPA layer', { exact: true }).press('Home')
    await expect(dpaAllLayerTotal).toHaveText(dpaBeforeLayer)
    const denseGate = dpaWeights.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^gate_up_proj/ }) })
    await denseGate.locator('summary').click()
    await expect(denseGate).toContainText('Payload Shape [3072, 6144]')
    await expect(denseGate).toContainText('FP8 · mlp')
    await fits('DPA mixed topology and Dense selection')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(dpaPrecision.getByLabel('Dense MLP 精度', { exact: true })).toHaveValue('fp8')
    await expect(dpaPrecision.getByLabel('Routed MoE 精度', { exact: true })).toHaveValue('w4afp8')
    await expect(dpaAllLayerTotal).toHaveText(dpaBeforeLayer)
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await dpaWeights.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `dpa-mixed-${width}.png`), animations: 'disabled' })
    }
    const beforeProcessedDpa = await dpaAllLayerTotal.innerText()
    const beforeProcessedDense = await dpaTotals.locator('output').first().innerText()
    await dpaPrecision.getByLabel('W4A8 权重阶段', { exact: true }).selectOption('processed')
    await expect(dpaAllLayerTotal).not.toHaveText(beforeProcessedDpa)
    await expect(dpaTotals.locator('output').first()).toHaveText(beforeProcessedDense)
    await expect(page).toHaveURL(/w4stage=processed/)
    for (const layer of [1, 2, 3]) {
      await page.getByLabel('DPA layer', { exact: true }).press('ArrowRight')
      await expect(page.getByLabel('DPA layer', { exact: true })).toHaveValue(String(layer))
    }
    await dpaExpert.locator('summary').click()
    await expect(dpaExpert).toContainText('Weight scale [32, 12, 16384] · BF16')
    await expect(dpaExpert).toContainText('Input scale [1] · FP32 · 4 B')
    const dpaMetadata = page.getByLabel('W4A8 独立运行元数据', { exact: true })
    await dpaMetadata.locator('summary').click()
    await expect(dpaMetadata).toContainText('3,972 B')
    await expect(dpaMetadata).toContainText('7 个独立分配，4 个别名不重复计数')
    await fits('DPA W4 post-load scales and unique metadata')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(dpaPrecision.getByLabel('W4A8 权重阶段', { exact: true })).toHaveValue('processed')
    await expect(dpaWeights).toContainText('W4A8 已按后处理布局统计')
    await dpaPrecision.getByRole('button', { name: '统一位宽 · 理论对照', exact: true }).click()
    await expect(page.getByLabel('DPA 权重位宽', { exact: true })).toHaveValue('4')
    await expect(page).not.toHaveURL(/precision=mixed/)
    await fits('DPA mixed reload and exit')
    await page.goto(`${base}#/models/qwen3-8b`, { waitUntil: 'networkidle' })
    await page.getByRole('tab', { name: '权重清单', exact: true }).click()
    await page.getByRole('link', { name: '深入：Attention DP 请求分组与通信实验 ↗', exact: true }).click()
    await expect(page).toHaveURL(/models\/qwen3-8b\/dpa/)
    await expect(page.getByLabel('DPA ep', { exact: true })).toHaveCount(0)
    await expect(page.getByLabel('DPA layer', { exact: true })).toHaveAttribute('max', '35')
    await page.goto(`${base}#/models/qwen3-8b/dpa?tp=8&dp=4&groups=3,1,0,2&rank=5&s=128&precision=mixed&mlp=fp8`, { waitUntil: 'networkidle' })
    const qwenDpaInternal = page.getByLabel('GQA DPA 内部张量', { exact: true })
    const qwenDpaCache = page.getByLabel('GQA DPA 缓存归属', { exact: true })
    await expect(dpaPrecision.getByRole('combobox')).toHaveCount(1)
    await expect(dpaTotals).toContainText('36 层 / 本 rank')
    await expect(dpaTotals).toContainText('2,190,200,832 B')
    await expect(dpaFlow).toContainText('K/V heads 4–7')
    await expect(dpaFlow).toContainText('并非再次跨卡 ReduceScatter')
    await expect(qwenDpaCache).toContainText('[0, 128, 2, 4, 128]')
    await expect(dpaMemory).toContainText('普通 TP 全卡缓存 108 MiB；DPA 全卡缓存 108 MiB')
    await qwenDpaInternal.locator('summary').click()
    await expect(qwenDpaInternal.locator('[data-tensor-id="qkv"]')).toContainText('[0, 3072]')
    await expect(qwenDpaInternal.locator('[data-tensor-id="gate-up"]')).toContainText('98,304 B')
    await fits('Qwen DPA idle group, full cache conservation and padded MLP')
    await page.getByRole('button', { name: 'DPA 观察 Rank 0', exact: true }).click()
    await expect(qwenDpaCache).toContainText('[3, 128, 2, 4, 128]')
    await expect(qwenDpaCache).toContainText('28,311,552 B')
    await expect(qwenDpaInternal.locator('[data-tensor-id="qkv"]')).toContainText('[3, 3072]')
    const qwenDpaQ = dpaWeights.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^q_proj/ }) })
    await qwenDpaQ.locator('summary').click()
    await expect(qwenDpaQ).toContainText('[16 × 128, 4096]')
    const qwenDpaFused = page.getByLabel('Qwen3 Dense 融合布局', { exact: true })
    await qwenDpaFused.locator('summary').click()
    await expect(qwenDpaFused).toContainText('18,878,976 B')
    await expect(qwenDpaFused).toContainText('输入 [16,4096]')
    await expect(qwenDpaFused).toContainText('DPA 汇合缓冲（含 padding）')
    await fits('Qwen DPA active rank and fused Dense buffer rows')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await qwenDpaCache.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `qwen-dpa-cache-${width}.png`), animations: 'disabled' })
    }
    await page.getByLabel('DPA dp', { exact: true }).press('Home')
    await expect(qwenDpaQ).toContainText('[4 × 128, 4096]')
    await expect(dpaTotals).toContainText('1,057,738,752 B')
    await expect(qwenDpaFused).toContainText('18,878,976 B')
    await expect(qwenDpaFused).toContainText('输入 [3,4096]')
    await page.getByLabel('DPA 阶段', { exact: true }).selectOption('prefill')
    await expect(qwenDpaInternal.locator('[data-tensor-id="qkv"]')).toContainText('[384, 768]')
    await expect(qwenDpaFused).toContainText('输入 [384,4096]')
    await dpaPrecision.getByLabel('Dense MLP 精度', { exact: true }).selectOption('bf16')
    await expect(dpaTotals).toContainText('1,737,050,112 B')
    await expect(qwenDpaFused).toContainText('37,748,736 B')
    await fits('Qwen DPA contraction, Prefill and mixed weight update')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(page.getByLabel('DPA 阶段', { exact: true })).toHaveValue('prefill')
    await expect(dpaPrecision.getByLabel('Dense MLP 精度', { exact: true })).toHaveValue('bf16')
    await expect(dpaTotals).toContainText('1,737,050,112 B')
    await page.getByLabel('DPA tp', { exact: true }).press('Home')
    // DP was already 1: wait for the TP transition itself, not that unchanged value.
    await expect(page.getByLabel('DPA tp', { exact: true })).toHaveAttribute('aria-valuetext', '1')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('max', '0')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('aria-valuetext', '1')
    await page.getByLabel('DPA tp', { exact: true }).press('End')
    await expect(page.getByLabel('DPA tp', { exact: true })).toHaveAttribute('aria-valuetext', '8')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('max', '3')
    await page.getByLabel('DPA dp', { exact: true }).press('End')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('aria-valuetext', '8')
    await expect(page).toHaveURL(/dp=8/)
    await fits('Qwen DPA reload and first DP operation after TP bounce')
    await page.getByRole('navigation', { name: 'DPA 模型对照', exact: true }).getByRole('link', { name: 'GLM-5.2 · MLA / MoE', exact: true }).click()
    await expect(page.getByLabel('DPA layer', { exact: true })).toHaveAttribute('max', '77')
    await expect(page.getByLabel('DPA ep', { exact: true })).toHaveAttribute('aria-valuetext', '4')
    await page.getByRole('navigation', { name: 'DPA 模型对照', exact: true }).getByRole('link', { name: 'Qwen3-8B · GQA / Dense', exact: true }).click()
    await expect(page.getByLabel('DPA layer', { exact: true })).toHaveAttribute('max', '35')
    await expect(page.getByLabel('DPA ep', { exact: true })).toHaveCount(0)
    await expect(page.getByLabel('DPA layer', { exact: true })).toHaveValue('0')
    await fits('DPA model switch resets model-specific bounds and expert controls')
    for (const [id, E, H, I, lastFormat] of [
      ['glm-5-2', 256, 6144, 2048, 'mxfp8'],
      ['glm-5-3-flash', 288, 4096, 2048, 'mxfp8'],
      ['kimi-k3', 896, 3584, 3072, 'mxfp8'],
      ['deepseek-v4-flash', 256, 4096, 2048, 'fp4-load'],
    ]) {
      await page.goto(`${base}#/models/${id}?layer=3&node=moe&view=weights&b=3&s=4096&tp=4&ep=2&replicas=2&rank=7&wbits=4&packing=fp8-block`, { waitUntil: 'networkidle' })
      const packing = page.getByRole('region', { name: '专家权重加载布局', exact: true })
      await expect(packing).toBeVisible()
      // Hash-router transitions may briefly retain the previous model's visible panel.
      await expect(packing).toContainText(`E_local = ${E} / EP 2 = ${E / 2}，H = ${H}`)
      await expect(packing.getByRole('slider')).toHaveAttribute('aria-valuetext', 'FP8 · 128×128')
      const theory = page.getByText('本模块 / rank', { exact: true }).locator('..')
      const theoryBefore = await theory.textContent()
      await packing.getByRole('slider').press('End')
      await expect(page).toHaveURL(new RegExp(`packing=${lastFormat}`))
      await expect(packing).toContainText(`[${E / 2}, ${I}, ${lastFormat === 'fp4-load' ? H / 2 : H}]`)
      const logicalElements = 3 * E * H * I / 4
      const allocation = logicalElements * (lastFormat === 'fp4-load' ? 0.5 + 4 / 32 : 1 + 1 / 32)
      await expect(packing).toContainText(`${allocation.toLocaleString('en-US')} B`)
      assert.equal(await theory.textContent(), theoryBefore, 'packing does not change the uniform-bit ledger')
      await fits(`${id} expert packing`)
      await page.getByLabel('Rank 实验 EP', { exact: true }).press('End')
      await expect(page).toHaveURL(/ep=4/)
      await expect(packing).toContainText(`[${E / 4}, ${2 * I}, ${lastFormat === 'fp4-load' ? H / 2 : H}]`)
      await expect(packing).toContainText(`${allocation.toLocaleString('en-US')} B`)
      await page.getByLabel('Rank 实验 TP', { exact: true }).press('End')
      await expect(page).toHaveURL(/tp=8/)
      await expect(packing).toContainText(`${(allocation / 2).toLocaleString('en-US')} B`)
      await page.getByLabel('独立 DP 副本数', { exact: true }).press('End')
      await expect(page).toHaveURL(/replicas=8/)
      await expect(packing).toContainText(`${(allocation / 2 * 64).toLocaleString('en-US')} B`)
      await page.reload({ waitUntil: 'networkidle' })
      await expect(packing).toContainText(`Rank 7：E_local`)
      await expect(packing).toContainText(`${(allocation / 2).toLocaleString('en-US')} B`)
      for (const [key, value] of Object.entries({ b: '3', s: '4096', wbits: '4', tp: '8', ep: '4', replicas: '8', rank: '7', packing: lastFormat })) {
        assert.equal(new URLSearchParams(new URL(page.url()).hash.split('?')[1]).get(key), value)
      }
      await fits(`${id} expert packing topology and reload`)
      if (process.env.MODEL_QA_SCREENSHOTS && id === 'deepseek-v4-flash') {
        await packing.evaluate(el => el.scrollIntoView({ block: 'start' }))
        await page.evaluate(() => window.scrollBy(0, -85))
        await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `expert-packing-${width}.png`), animations: 'disabled' })
      }
      await packing.getByRole('slider').press('Home')
      await expect(page).not.toHaveURL(/packing=/)
      await expect(packing).toContainText('无 scale 张量')
    }
    await page.goto(`${base}#/models/kimi-k3?layer=3&node=moe&view=weights&b=3&s=4096&tp=4&ep=2&replicas=2&rank=7&wbits=4&precision=mixed&mlp=fp8&shared=bf16&experts=w4afp8`, { waitUntil: 'networkidle' })
    const mixedControls = page.getByRole('region', { name: '按模块选择精度', exact: true })
    await expect(mixedControls.getByLabel('Routed MoE 精度', { exact: true })).toHaveValue('w4afp8')
    const mixedRank = page.getByRole('region', { name: '逐 rank 并行实验', exact: true })
    await expect(mixedRank).toContainText('当前按模块混合精度')
    await expect(mixedRank.getByLabel('Rank 实验权重位宽', { exact: true })).toHaveCount(0)
    await expect(page.getByRole('region', { name: '专家权重加载布局', exact: true })).toHaveCount(0)
    const routerDetail = mixedRank.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^gate.weight/ }) })
    await routerDetail.locator('summary').click()
    await expect(routerDetail).toContainText('FP32 · router')
    await expect(routerDetail).toContainText('24.5 MiB')
    const expertDetail = mixedRank.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^experts.gate_up_proj/ }) })
    await expertDetail.locator('summary').click()
    await expect(expertDetail).toContainText('Payload Shape [448, 3072, 1792]')
    await expect(expertDetail).toContainText('Input scale [448, 2]')
    const rowValue = page.getByText('本模块 / rank', { exact: true }).locator('..')
    const beforeShared = await rowValue.textContent()
    await mixedControls.getByLabel('Dense MLP 精度', { exact: true }).selectOption('bf16')
    await expect(page).toHaveURL(/mlp=bf16/)
    assert.equal(await rowValue.textContent(), beforeShared, 'Dense precision does not modify the current MoE layer')
    await mixedControls.getByLabel('Shared MLP 精度', { exact: true }).selectOption('fp8')
    await expect(page).toHaveURL(/shared=fp8/)
    await expect(rowValue).not.toHaveText(beforeShared)
    await expect(routerDetail).toContainText('FP32 · router')
    await fits('mixed precision shared ledger')
    await page.getByLabel('Rank 实验 EP', { exact: true }).press('End')
    await expect(page).toHaveURL(/ep=4/)
    await expect(expertDetail).toContainText('Payload Shape [224, 6144, 1792]')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(mixedControls.getByLabel('Shared MLP 精度', { exact: true })).toHaveValue('fp8')
    await expect(page.getByLabel('实时权重结果', { exact: true })).toContainText('含 scale')
    const audit = page.getByRole('region', { name: 'Kimi 权重口径核对', exact: true })
    const auditBody = audit.getByLabel('Kimi 文件差额与审计说明', { exact: true })
    await expect(auditBody).not.toHaveAttribute('open', '')
    await auditBody.locator(':scope > summary').focus()
    await page.keyboard.press('Enter')
    await expect(audit).toContainText('1.389 TB')
    await expect(audit).toContainText('1.555 TB')
    await expect(audit).toContainText('约 1.56 TB')
    await expect(audit).toContainText('1,560,936,091,448 B')
    await expect(audit).toContainText('497,220 个张量')
    const bridge = auditBody.locator('details').filter({ has: page.locator('summary').filter({ hasText: '展开逐项差额' }) })
    await bridge.locator('summary').focus()
    await page.keyboard.press('Enter')
    await expect(bridge).toContainText('1,560,860,324,864 B')
    await expect(bridge).toContainText('22,244,864 B')
    await expect(bridge).toContainText('4,416 B')
    await fits('native Kimi exact reconciliation expanded')
    await bridge.locator('summary').click()
    const nativeDtypes = auditBody.locator('details').filter({ has: page.locator('summary').filter({ hasText: '查看原生模块与 dtype' }) })
    await nativeDtypes.locator('summary').click()
    await expect(nativeDtypes).toContainText('Router · BF16')
    await expect(nativeDtypes).toContainText('1,181,745,152 B')
    await expect(nativeDtypes).toContainText('[3072, 1792]')
    await fits('native Kimi dtype and storage shapes expanded')
    await nativeDtypes.locator('summary').click()
    const evidence = auditBody.locator('details').filter({ has: page.locator('summary').filter({ hasText: '审计方法、来源与验证边界' }) })
    await evidence.locator('summary').click()
    await expect(evidence).toContainText('没有下载或哈希校验约 1.56 TB 的权重载荷')
    await expect(evidence.getByRole('link', { name: '官方 ModelScope 权重目录 ↗', exact: true })).toHaveAttribute('href', 'https://modelscope.cn/models/moonshotai/Kimi-K3')
    await fits('native Kimi evidence boundaries expanded')
    await evidence.locator('summary').click()
    await auditBody.locator(':scope > summary').click()
    await fits('mixed precision reload and Kimi audit')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await audit.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `mixed-audit-${width}.png`), animations: 'disabled' })
    }
    const beforeW4Processed = await rowValue.textContent()
    await mixedControls.getByLabel('W4A8 权重阶段', { exact: true }).selectOption('processed')
    await expect(rowValue).not.toHaveText(beforeW4Processed)
    await expect(page).toHaveURL(/w4stage=processed/)
    await expertDetail.locator('summary').click()
    await expect(expertDetail).toContainText('Payload Shape [224, 6144, 1792]')
    await expect(expertDetail).toContainText('Weight scale [224, 7, 24576] · BF16')
    await expect(expertDetail).toContainText('Input scale [1] · FP32 · 4 B')
    const metadata = page.getByLabel('W4A8 独立运行元数据', { exact: true })
    await metadata.locator('summary').focus()
    await page.keyboard.press('Enter')
    await expect(metadata).toContainText('27,780 B')
    await expect(metadata).toContainText('同一存储的别名：b_strides1')
    await mixedControls.getByRole('button', { name: '按模块混合精度', exact: true }).click()
    await expect(mixedControls.getByLabel('W4A8 权重阶段', { exact: true })).toHaveValue('processed')
    await fits('Kimi W4 post-load and metadata alias accounting')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await metadata.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `w4-metadata-${width}.png`), animations: 'disabled' })
    }
    await page.getByLabel('Rank 实验 TP', { exact: true }).press('End')
    await expect(expertDetail).toContainText('Weight scale [224, 7, 12288] · BF16')
    await page.getByLabel('Rank 实验 EP', { exact: true }).press('Home')
    const downDetail = mixedRank.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^experts.down_proj/ }) })
    await downDetail.locator('summary').click()
    await expect(downDetail).toContainText('Weight scale [896, 3, 3584] · BF16')
    await expect(metadata).toContainText('111,108 B')
    await fits('Kimi W4 non-four-wide scale and EP metadata')
    await page.reload({ waitUntil: 'networkidle' })
    await expect(mixedControls.getByLabel('W4A8 权重阶段', { exact: true })).toHaveValue('processed')
    await expect(mixedRank).toContainText('Weight scale [896, 3, 3584] · BF16')
    await mixedControls.getByLabel('W4A8 权重阶段', { exact: true }).selectOption('allocated')
    await expect(page).not.toHaveURL(/w4stage=/)
    await expect(mixedRank).toContainText('Weight scale [896, 3584, 3] · FP32')
    await mixedControls.getByRole('button', { name: '统一位宽 · 理论对照', exact: true }).click()
    await expect(page).not.toHaveURL(/precision=mixed/)
    await expect(page).toHaveURL(/wbits=4/)
    await expect(mixedRank.getByLabel('Rank 实验权重位宽', { exact: true })).toHaveAttribute('aria-valuetext', '4-bit')
    await page.goto(`${base}#/models/kimi-k3?view=weights&tp=8&ep=1&rank=7&layer=3`, { waitUntil: 'networkidle' })
    const native = page.getByLabel('Kimi 原生加载基线', { exact: true })
    await native.locator(':scope > summary').focus()
    await page.keyboard.press('Enter')
    await expect(native).toContainText('206,668,769,776 B')
    await expect(native).toContainText('本地专家 [0, 896)')
    const fusedNative = native.getByLabel('MXFP4 初始融合分配', { exact: true })
    await fusedNative.locator('summary').click()
    await expect(fusedNative).toContainText('w13_weight [896, 768, 1792]')
    await expect(fusedNative).toContainText('w2_weight_scale [896, 3584, 12]')
    await fits('Kimi native TP8 initial allocation containers')
    await page.getByLabel('Rank 实验 EP', { exact: true }).press('End')
    await expect(native).toContainText('206,151,756,272 B')
    await expect(native).toContainText('本地专家 [784, 896)')
    await expect(fusedNative).toContainText('w13_weight [112, 6144, 1792]')
    await page.getByLabel('独立 DP 副本数', { exact: true }).press('ArrowRight')
    await page.getByLabel('观察 DP 副本', { exact: true }).selectOption('1')
    await page.getByRole('button', { name: '观察 Rank 15', exact: true }).click()
    await expect(native).toContainText('DP 副本 1，TP rank 7')
    await expect(native).toContainText('3,298,428,100,352 B')
    await fits('Kimi native EP ownership and independent DP copies')
    await native.getByLabel('原生权重模块', { exact: true }).selectOption('router')
    const gateNative = native.locator('details').filter({ has: page.locator('summary').filter({ hasText: /block_sparse_moe.gate.weight/ }) })
    await gateNative.locator('summary').click()
    await expect(gateNative).toContainText('文件 [896, 7168] · BF16 → 本 rank [896, 7168] · BF16')
    await native.getByLabel('原生权重模块', { exact: true }).selectOption('attention')
    const aLogNative = native.locator('details').filter({ has: page.locator('summary').filter({ hasText: /self_attn.A_log/ }) })
    await aLogNative.locator('summary').click()
    await expect(aLogNative).toContainText('文件 [128] · F32 → 本 rank [1, 1, 12, 1] · F32')
    await expect(aLogNative).toContainText('head 84–95')
    await fits('Kimi native attention load narrowing')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await native.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `native-layout-${width}.png`), animations: 'disabled' })
    }
    await page.reload({ waitUntil: 'networkidle' })
    await native.locator(':scope > summary').click()
    await expect(native).toContainText('3,298,428,100,352 B')
    await page.getByLabel('Rank 实验 TP', { exact: true }).press('Home')
    await expect(native).toContainText('1,562,464,095,360 B')
    await expect(native).toContainText('EP rank 0，MoE-TP rank 0')
    await fits('Kimi native reload and TP1 clamp')
    await native.getByLabel('Kimi 原生权重阶段', { exact: true }).selectOption('processed')
    await expect(page).toHaveURL(/native=processed/)
    await expect(native).toContainText('1,564,681,137,280 B')
    await expect(native).toContainText('已核对持久张量 / rank')
    const postDetails = native.getByLabel('Kimi 后处理明细', { exact: true })
    const nativeExpertPost = postDetails.locator('details').filter({ has: page.locator('summary').filter({ hasText: 'MXFP4 后处理：9 个参数容器' }) })
    await nativeExpertPost.locator(':scope > summary').click()
    await expect(nativeExpertPost).toContainText('w13_weight_bias [896, 6144] · F32')
    await expect(nativeExpertPost).toContainText('gemm1_alpha [896] · F32')
    await expect(nativeExpertPost).toContainText('w13_weight_scale [896, 6144, 112] · F8_E4M3FN view')
    await fits('Kimi native processed nine parameters')
    await page.getByLabel('Rank 实验 TP', { exact: true }).press('End')
    await expect(native).toContainText('207,481,242,608 B')
    await expect(page.getByLabel('Rank 实验 EP', { exact: true })).toBeEnabled()
    await expect(page.getByLabel('Rank 实验 EP', { exact: true })).toHaveAttribute('max', '3')
    await page.getByLabel('Rank 实验 EP', { exact: true }).press('End')
    await expect(native).toContainText('206,446,479,088 B')
    await expect(nativeExpertPost).toContainText('gemm1_alpha [112] · F32')
    const derivedPost = postDetails.locator('details').filter({ has: page.locator('summary').filter({ hasText: '持久派生张量、padding 与重排索引' }) })
    await derivedPost.locator(':scope > summary').click()
    await expect(derivedPost).toContainText('KDA merged f_a / b padding · 3,956,736 B')
    await expect(derivedPost).toContainText('w13_weight row indices · 49,152 B')
    await fits('Kimi native processed TP8 padding and shared indices')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await native.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `native-postload-${width}.png`), animations: 'disabled' })
    }
    await page.reload({ waitUntil: 'networkidle' })
    await native.locator(':scope > summary').click()
    await expect(native.getByLabel('Kimi 原生权重阶段', { exact: true })).toHaveValue('processed')
    await expect(native).toContainText('206,446,479,088 B')
    await native.getByLabel('Kimi 原生权重阶段', { exact: true }).selectOption('initial')
    await expect(page).not.toHaveURL(/native=/)
    await expect(native).toContainText('206,151,756,272 B')
    await expect(native.getByLabel('原生权重模块', { exact: true })).toBeVisible()
    await fits('Kimi native stage reload and initial restoration')
    await page.goto(`${base}#/models/glm-5-2/dpa?tp=8&dp=8&ep=8`, { waitUntil: 'networkidle' })
    await page.getByLabel('DPA tp', { exact: true }).press('Home')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('max', '0')
    await expect(page.getByLabel('DPA ep', { exact: true })).toHaveAttribute('aria-valuetext', '1')
    await page.getByLabel('DPA tp', { exact: true }).press('End')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('max', '3')
    await page.getByLabel('DPA dp', { exact: true }).press('End')
    await expect(page.getByLabel('DPA dp', { exact: true })).toHaveAttribute('aria-valuetext', '8')
    await page.getByLabel('DPA ep', { exact: true }).press('End')
    await expect(page.getByLabel('DPA ep', { exact: true })).toHaveAttribute('aria-valuetext', '8')
    await expect(page).toHaveURL(/dp=8/)
    await expect(page).toHaveURL(/ep=8/)
    await fits('DPA sliders recover after shrinking and expanding native range bounds')
    await page.goto(`${base}#/models/kimi-k3?view=weights&node=moe&layer=3&tp=8&ep=8&replicas=8&rank=63&precision=mixed&experts=w4afp8`, { waitUntil: 'networkidle' })
    const compactRank = page.getByRole('region', { name: '逐 rank 并行实验', exact: true })
    const replicaPicker = compactRank.getByLabel('观察 DP 副本', { exact: true })
    const compactScope = page.getByLabel('实时权重结果', { exact: true })
    const frozenScope = await compactScope.textContent()
    await expect(replicaPicker.locator('option')).toHaveCount(8)
    await expect(compactRank.getByRole('button', { name: /^观察 Rank / })).toHaveCount(8)
    await expect(page.getByLabel('Kimi 文件差额与审计说明', { exact: true })).not.toHaveAttribute('open', '')
    await expect(page.getByLabel('专家归属与通信组', { exact: true })).not.toHaveAttribute('open', '')
    for (let replica = 0; replica < 8; replica++) {
      await replicaPicker.selectOption(String(replica))
      await expect(replicaPicker).toHaveValue(String(replica))
      const selectedRank = replica * 8 + 7
      await expect(compactRank.getByRole('heading', { name: `Rank ${selectedRank} · DP ${replica} / TP local 7`, exact: true })).toBeVisible()
      const buttons = compactRank.getByRole('button', { name: /^观察 Rank / })
      assert.deepEqual(await buttons.evaluateAll(nodes => nodes.map(n => n.getAttribute('aria-label'))), Array.from({ length: 8 }, (_, local) => `观察 Rank ${replica * 8 + local}`))
      await expect(compactScope).toHaveText(frozenScope)
    }
    await compactRank.getByRole('button', { name: '观察 Rank 56', exact: true }).click()
    await expect(compactRank.getByRole('button', { name: '观察 Rank 56', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await replicaPicker.selectOption('1')
    await expect(compactRank.getByRole('heading', { name: 'Rank 8 · DP 1 / TP local 0', exact: true })).toBeVisible()
    await expect(compactRank.getByLabel('当前模块权重小计', { exact: true })).toContainText('B')
    await expect(compactScope).toHaveText(frozenScope)
    await fits('compact rank navigator reaches every replica without changing scope totals')
    if (process.env.MODEL_QA_SCREENSHOTS) {
      await replicaPicker.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.evaluate(() => window.scrollBy(0, -85))
      await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `weight-reading-ranks-${width}.png`), animations: 'disabled' })
    }
    const readingUrl = page.url()
    for (const id of ['model-rank-details', 'model-native-details']) {
      const disclosure = page.locator(`#${id}`)
      await disclosure.locator(':scope > summary').focus()
      await page.keyboard.press('Enter')
      await expect(disclosure).not.toHaveAttribute('open', '')
      await page.keyboard.press('Enter')
      await expect(disclosure).toHaveAttribute('open', '')
      await expect(page).toHaveURL(readingUrl)
    }
    await fits('weight scope keyboard navigation preserves hash route and numerical conditions')
    if (process.env.MODEL_QA_SCREENSHOTS) await page.screenshot({ path: join(process.env.MODEL_QA_SCREENSHOTS, `weight-reading-audit-${width}.png`), animations: 'disabled' })
    await page.reload({ waitUntil: 'networkidle' })
    await expect(replicaPicker).toHaveValue('1')
    await expect(compactRank.getByRole('button', { name: '观察 Rank 8', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(compactScope).toHaveText(frozenScope)
    await fits('compact rank deep link reload and default disclosures')
    assert.deepEqual(errors, [], `${width}px runtime errors`)
    await page.close()
    console.log(`Browser interactions passed at ${width}px: V4, GLM, Kimi; TP/DP/EP; V4.1 source ownership, cache formats, Engram packing and URL reload.`)
  }
  console.log(`${checks} viewport overflow checks passed. Browser: ${browser.version()}. No GPU inference tested.`)
} finally {
  await browser.close()
}
