import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {readFile} from 'node:fs/promises'
const require=createRequire(import.meta.url),modulePath=process.env.MODEL_QA_PLAYWRIGHT||'playwright'
const {chromium}=require(modulePath),{expect}=require(`${modulePath}/test`)
const base=process.env.MODEL_QA_BASE||'http://127.0.0.1:4186/AI_Infra_Tutor_Page/'
const browser=await chromium.launch({headless:true,...(process.env.MODEL_QA_CHANNEL?{channel:process.env.MODEL_QA_CHANNEL}:{})})
const privateCsv='Name,Type,Task Start Time(us),Task Duration(us),Input Shapes,Input Data Types,Input Formats,Device ID,Stream ID\n"private/path/<img src=https://evil.invalid/SECRET>",,100,10,"2,4;4,3",BF16;BF16,ND;ND,7,0\nprivate/path/SECRET,,120,20,"2,4;4,3",BF16;BF16,ND;ND,7,0'
try{
  for(const width of [360,390,768,1440]){
    const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'})
    page.setDefaultTimeout(15000)
    const errors=[],requests=[]
    page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({method:r.method(),url:r.url()}))
    await page.route('**/*',route=>new URL(route.request().url()).origin===new URL(base).origin?route.continue():route.abort())
    const fit=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow at ${width}`)
    const upload=async(label,text,name='profile.csv')=>page.getByLabel(`导入${label}`,{exact:true}).setInputFiles({name,mimeType:name.endsWith('.json')?'application/json':'text/csv',buffer:Buffer.from(text)})
    await page.goto(`${base}#/`,{waitUntil:'networkidle'})
    await page.getByRole('link').filter({hasText:'Profiling 分析工作台'}).click()
    await expect(page.getByRole('heading',{name:'Profiling 分析工作台',exact:true})).toBeVisible()
    await page.getByRole('button',{name:'加载合成 A/B 示例',exact:true}).click()
    const summary=page.getByLabel('采样摘要',{exact:true})
    await expect(summary).toContainText('160 次调用')
    await expect(page.getByLabel('热点清单',{exact:true})).toContainText('LightningIndexer')
    await fit()
    const initial=await page.getByTestId('profile-whatif').innerText()
    await page.getByLabel('假设加速倍数',{exact:true}).fill('4')
    await expect(page.getByTestId('profile-whatif')).not.toHaveText(initial,{useInnerText:true})
    await page.getByLabel('假设加速倍数',{exact:true}).fill('0')
    await expect(page.getByRole('alert')).toContainText('1～100')
    await page.getByLabel('假设加速倍数',{exact:true}).fill('2')
    await page.getByRole('tab',{name:'A/B 回归对照',exact:true}).click()
    await expect(page.getByLabel('A/B 对照结果',{exact:true})).toContainText('调用次数不同')
    await expect(page.getByTestId('profile-diff')).toHaveCount(0)
    await page.getByRole('checkbox',{name:/我已核对 A\/B/}).check()
    await expect(page.getByTestId('profile-diff')).toBeVisible()
    await expect(page.getByLabel('A/B 对照结果',{exact:true})).toContainText('1.2×')
    await fit()
    if(process.env.MODEL_QA_SCREENSHOTS){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`${process.env.MODEL_QA_SCREENSHOTS}/profiling-compare-${width}.png`,fullPage:true})}
    await page.getByRole('tab',{name:'热点与优化优先级',exact:true}).click()
    await page.getByRole('button',{name:'查看热点 2 MatMul',exact:true}).click()
    await page.getByRole('link',{name:'带入热点进行理论校核 →',exact:true}).click()
    await expect(page.getByLabel('Profiling 热点校核',{exact:true})).toBeVisible()
    assert.ok(!JSON.stringify(await page.evaluate(()=>history.state)).includes('7168'),'shape stays out of browser history')
    await page.getByRole('button',{name:'确认语义并填入候选 Shape / P50',exact:true}).click()
    await expect(page.getByLabel('M · 输出行数',{exact:true})).toHaveValue('128')
    await expect(page.getByLabel('实测耗时',{exact:true})).toHaveValue('200')
    await page.getByRole('link',{name:'Profiling 分析',exact:true}).click()
    await expect(summary).toContainText('160 次调用')
    const aSlot=page.getByRole('region',{name:'基线 A导入',exact:true})
    await aSlot.locator('summary').filter({hasText:'范围与稳态筛选'}).click()
    await page.getByLabel('基线 AStep',{exact:true}).selectOption('1')
    await page.getByRole('button',{name:'应用基线 A筛选',exact:true}).click()
    await expect(summary).toContainText('20 次调用')
    await page.getByLabel('基线 Afrom',{exact:true}).fill('100')
    await page.getByLabel('基线 Ato',{exact:true}).fill('50')
    await page.getByRole('button',{name:'应用基线 A筛选',exact:true}).click()
    await expect(aSlot.getByRole('alert')).toContainText('时间窗口')
    await aSlot.getByRole('button',{name:'重置筛选',exact:true}).click()
    await expect(summary).toContainText('160 次调用')
    if(process.env.MODEL_QA_SCREENSHOTS){await aSlot.locator('summary').filter({hasText:'范围与稳态筛选'}).click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`${process.env.MODEL_QA_SCREENSHOTS}/profiling-hotspots-${width}.png`,fullPage:true})}
    await upload('基线 A',privateCsv,'private-SECRET.csv')
    await expect(summary).toContainText('2 次调用')
    await expect(page.getByLabel('热点清单',{exact:true})).toContainText('<img src=https://evil.invalid/SECRET>')
    const downloadPromise=page.waitForEvent('download')
    await page.getByRole('button',{name:'导出匿名统计',exact:true}).click()
    const download=await downloadPromise,text=await readFile(await download.path(),'utf8')
    for(const needle of ['SECRET','private','2,4;4,3','BF16','MatMul','selectedDevice','origin'])assert.ok(!text.includes(needle),needle)
    assert.equal(JSON.parse(text).baseline.calls,2)
    assert.equal(await page.locator('img[src*="evil.invalid"]').count(),0)
    const trace=JSON.stringify({displayTimeUnit:'ns',traceEvents:[{ph:'M',name:'process_name',pid:4,args:{name:'Ascend Hardware'}},{ph:'X',name:'MatMul',pid:4,tid:0,ts:100,dur:10,args:{'Task Type':'AI_CORE'}},{ph:'X',name:'PythonHost',pid:1,tid:0,ts:0,dur:9999}]})
    await upload('基线 A',trace,'trace_view.json')
    await expect(summary).toContainText('1 次调用')
    await expect(summary).toContainText('10 µs')
    await expect(page.getByLabel('热点清单',{exact:true})).not.toContainText('PythonHost')
    await upload('基线 A','Name,Duration(us)\nNoTimestamp,10')
    await expect(summary).toContainText('不可计算')
    await upload('基线 A','Name,Duration\nUnitless,2')
    await expect(aSlot.getByRole('alert')).toContainText('没有明确单位')
    await page.getByLabel('基线 A无单位时间列',{exact:true}).selectOption('ms')
    await upload('基线 A','Name,Duration\nUnitless,2')
    await expect(summary).toContainText('2 ms')
    await upload('基线 A','[{"ph":','truncated.json')
    await expect(aSlot.getByRole('alert')).toContainText('截断')
    if(width===1440){
      const large=['Name,Type,Duration(us),Start Time(us),Step ID,Input Shapes,Input Data Types,Input Formats',...Array.from({length:4000},(_,i)=>`task${i},Op${i%30},1,${i*2},${i},"2,4;4,3",BF16;BF16,ND;ND`)].join('\n')
      await upload('基线 A',large)
      await expect(summary).toContainText('4000 次调用')
      await expect(page.getByRole('button',{name:'下一页',exact:true})).toBeEnabled()
      await page.getByRole('button',{name:'下一页',exact:true}).click()
      await expect(page.getByLabel('热点清单',{exact:true}).locator('tbody tr')).toHaveCount(10)
      const range=aSlot.locator('details').filter({has:page.locator('summary').filter({hasText:'范围与稳态筛选'})})
      if(await range.getAttribute('open')===null)await range.locator('summary').click()
      await expect(page.getByLabel('基线 AStep',{exact:true})).toHaveJSProperty('tagName','INPUT')
      await page.getByLabel('基线 AStep',{exact:true}).fill('3999')
      await page.getByRole('button',{name:'应用基线 A筛选',exact:true}).click()
      await expect(summary).toContainText('1 次调用')
    }
    await page.getByRole('button',{name:'清空全部数据',exact:true}).click()
    await expect(summary).toHaveCount(0)
    await expect(page.getByRole('alert')).toHaveCount(0)
    await page.getByRole('button',{name:'加载合成 A/B 示例',exact:true}).click()
    await expect(summary).toBeVisible()
    await page.reload({waitUntil:'networkidle'})
    await expect(summary).toHaveCount(0)
    const stored=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage},history:history.state}))
    assert.ok(!stored.includes('SECRET')&&!stored.includes('7168'))
    assert.ok(requests.every(r=>r.method==='GET'&&!r.url.includes('SECRET')))
    assert.deepEqual(errors,[])
    await fit();await page.close()
    console.log(`Profiling workbench ${width}px: worker import, hotspots, A/B, filters, theory drilldown, memory preservation, malformed data, export privacy, no overflow passed.`)
  }
}finally{await browser.close()}
