import { useEffect, useRef, useState, type SetStateAction } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, Download, ShieldCheck } from 'lucide-react'
import PageHeader from '@/components/PageHeader'
import PerformanceNav from '@/components/PerformanceNav'
import MultiRankTimeline from '@/components/MultiRankTimeline'
import { useMultiRankProfile } from '@/hooks/useMultiRankProfile'
import { anonymousRankReport, type RankConfig, type RankSettings, type RankMetrics } from '@/lib/multi-rank-profile'
import type { TimeUnit } from '@/lib/profile-import'

const control='mt-1 min-h-11 w-full min-w-0 rounded-lg border border-line bg-field px-3 py-2 text-sm text-ink'
const panel='min-w-0 rounded-2xl border border-line bg-surface p-4 sm:p-6'
const num=(n:number)=>n.toLocaleString('en-US',{maximumFractionDigits:2})
const us=(n:number|null)=>n===null?'尚不可比较':`${num(n)} µs`

function EventPicker({row,value,onChange}:{row:RankMetrics;value:string;onChange:(id:string)=>void}){
  const [search,setSearch]=useState(''),[page,setPage]=useState(0)
  const filtered=row.candidates.filter(e=>`${e.name} ${e.stream} ${e.step}`.toLowerCase().includes(search.toLowerCase())),shownPage=Math.min(page,Math.max(0,Math.ceil(filtered.length/30)-1))
  const shown=filtered.slice(shownPage*30,shownPage*30+30),selected=row.candidates.find(e=>e.id===value)
  return <div className="min-w-0 rounded-xl border border-line p-3"><h3 className="text-sm text-ink">Rank {row.label}</h3>
    <label className="mt-2 block text-xs text-muted">筛选通信事件<input aria-label={`Rank ${row.label} 事件搜索`} className={control} value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="名称 / Stream / Step"/></label>
    <label className="mt-2 block text-xs text-muted">人工配对的事件<select className={control} aria-label={`Rank ${row.label} 配对事件`} value={value} onChange={e=>onChange(e.target.value)}><option value="">未选择</option>{selected&&!shown.some(e=>e.id===value)&&<option value={value}>{selected.name} · {num(selected.start)} µs</option>}{shown.map(e=><option key={e.id} value={e.id}>{e.name.slice(0,100)} · {num(e.start)} µs · S{e.stream} · {us(e.duration)}</option>)}</select></label>
    {filtered.length>30&&<div className="mt-2 flex items-center gap-2 text-xs"><button className="button-secondary" disabled={!shownPage} onClick={()=>setPage(shownPage-1)}>前 30 条</button><span>{shownPage+1}/{Math.ceil(filtered.length/30)}</span><button className="button-secondary" disabled={(shownPage+1)*30>=filtered.length} onClick={()=>setPage(shownPage+1)}>后 30 条</button></div>}
    <p className="mt-2 text-xs leading-5 text-muted">{row.candidateCount} 个候选；名称分类需核对。{row.candidateTruncated?'仅列前 5000 个；请缩小观察窗口后重算。':''}</p>
    {selected&&<p className="mt-2 break-words text-xs leading-5 text-secondary">已选：{selected.name} · Stream {selected.stream} · Step {selected.step||'未标注'} · {us(selected.duration)}</p>}
  </div>
}

export default function MultiRankProfiling({active=true}:{active?:boolean}){
  const profile=useMultiRankProfile(),[editing,setEditing]=useState<{base:RankConfig|null;value:RankConfig|null}>({base:null,value:null}),[unit,setUnit]=useState<TimeUnit>('auto'),[exported,setExported]=useState(false)
  // Drafts belong to one worker result/config. Never render old rank IDs with a
  // replacement's metadata during the effect/worker response boundary.
  const draft=editing.base===profile.config?editing.value:profile.config
  const setDraft=(action:SetStateAction<RankConfig|null>)=>setEditing({base:profile.config,value:typeof action==='function'?action(draft):action})
  const directory=useRef<HTMLInputElement>(null)
  useEffect(()=>{directory.current?.setAttribute('webkitdirectory','')},[])
  useEffect(()=>{setExported(false)},[profile.config])
  const result=profile.result,dirty=JSON.stringify(draft)!==JSON.stringify(profile.config)
  const update=(change:Partial<RankConfig>)=>setDraft(c=>c?{...c,...change}:null)
  const rankEdit=(id:string,change:Partial<RankSettings>)=>setDraft(c=>c?{...c,pairingConfirmed:false,...('included'in change||'step'in change?{workloadConfirmed:false}:{}),...('offset'in change?{clockConfirmed:false}:{}),ranks:c.ranks.map(r=>r.id===id?{...r,...change}:r)}:null)
  const apply=()=>{if(draft)profile.analyze(draft)}
  const download=()=>{
    if(!result||dirty)return
    const url=URL.createObjectURL(new Blob([JSON.stringify(anonymousRankReport(result),null,2)],{type:'application/json'})),link=document.createElement('a')
    link.href=url;link.download='anonymous-multi-rank-profile.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExported(true)
  }
  return <div className="page-container py-8 text-secondary">
    <PerformanceNav/>
    <PageHeader eyebrow="PROFILE / MULTI-RANK" title="多 rank，放到同一条证据链" description="先核对时钟与采样范围，再对照计算、通信和等待。让可观察的差异与仍待验证的原因分开。" compact/>
    <div className="mb-6 flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-2 text-xs text-emerald-200"><ShieldCheck size={15}/>本地 Worker 解析 · 不上传 · 刷新即清空</span><Link to="/operators/guide" className="ml-auto inline-flex min-h-11 items-center gap-2 text-sm text-accent">Profiling 阅读教程 <ArrowRight size={14}/></Link></div>
    {dirty&&<div role="status" className="sticky top-16 z-20 mb-3 flex flex-wrap items-center gap-3 rounded-lg border border-amber-300/40 bg-surface p-3 text-sm text-amber-200">条件已修改，下方仍为上次结果。<button className="button-secondary" disabled={profile.busy} onClick={apply}>应用修改并重算</button></div>}
    {result&&<div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4" aria-label="多 rank 核心结果">{[['参与执行域',String(result.rows.length),'仅所选采样子集'],['最大计算覆盖',us(Math.max(...result.rows.map(r=>r.compute))),'区间并集，非累计工作量'],['最大等待覆盖',us(Math.max(...result.rows.map(r=>r.wait))),'等待不等同于网络传输'],['记录完成时差',us(result.completionSpread),'所选记录末尾，非请求端到端']].map(([label,value,note])=><div className="rounded-xl border border-line bg-surface p-4" key={label}><p className="text-xs text-muted">{label}</p><p className="mt-2 break-words text-xl font-medium text-ink">{value}</p><p className="mt-2 text-xs leading-5 text-muted">{note}</p></div>)}</div>}
    <section className={panel} aria-label="联合采样导入">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-medium text-ink">{profile.config?`已加载 ${profile.info.length} 个执行域`:'从真实采样或教学案例开始'}</h2>{!profile.config&&<p className="mt-2 text-xs leading-6 text-muted">文件多选：每文件独立采样。目录导入：同一输出目录的 Kernel / Trace 自动去重对账，再按设备/PID 分开。最多 64 个执行域、100 万条任务、256 MiB；每文件 ≤ 50 MiB。</p>}</div><button className="button-secondary" onClick={()=>{profile.clear();setDraft(null);setExported(false)}}>清空联合分析</button></div>
      <div className="mt-4 flex flex-wrap gap-2"><button className="button-primary" onClick={()=>profile.loadDemo('straggler')}>体验计算拖尾案例</button><button className="button-secondary" onClick={()=>profile.loadDemo('clock')}>体验时钟偏移案例</button></div>
      <details className="mt-4"><summary className="min-h-11 cursor-pointer py-3 text-sm text-accent">导入本地多 rank 数据（替换当前联合分析）</summary><div className="mt-2 grid gap-4 sm:grid-cols-3">
        <label className="min-w-0 text-xs text-muted">无单位时间列<select className={control} value={unit} onChange={e=>setUnit(e.target.value as TimeUnit)}><option value="auto">不明确则拒绝</option><option value="us">按 µs</option><option value="ms">按 ms</option><option value="ns">按 ns</option></select></label>
        <label className="min-w-0 text-xs text-muted">多个设备任务文件<input className="mt-2 block w-full min-w-0 text-xs file:mr-2 file:rounded-md file:border-0 file:bg-raised file:p-3 file:text-accent" type="file" multiple accept=".csv,.json" aria-label="导入多 rank 文件" onChange={e=>{const files=Array.from(e.target.files??[]);if(files.length)profile.loadFiles(files,unit);e.target.value=''}}/></label>
        <label className="min-w-0 text-xs text-muted">多个采样的父目录<input ref={directory} className="mt-2 block w-full min-w-0 text-xs file:mr-2 file:rounded-md file:border-0 file:bg-raised file:p-3 file:text-accent" type="file" multiple aria-label="导入多 rank 目录" onChange={e=>{const files=Array.from(e.target.files??[]);if(files.length)profile.loadFiles(files,unit);e.target.value=''}}/></label>
      </div><p className="mt-3 text-xs leading-6 text-muted">不读取日志、原始二进制和 profiler 元数据。单文件仅有耗时、没有起始时间时，请使用原单份分析。替换或清空会终止本页旧 Worker，不影响原 A/B 工作台。</p></details>
      {profile.busy&&<p role="status" className="mt-3 text-sm text-accent">{profile.progress||'正在本地重新计算…'} 可用“清空联合分析”取消。</p>}
      {profile.error&&<p role="alert" className="mt-3 break-words text-sm text-rose-200">{profile.error}</p>}
    </section>
    {profile.demo&&<section className="mt-4 rounded-xl border border-accent/30 bg-accent/5 p-4 text-sm leading-6" aria-label="合成案例说明"><strong className="font-medium text-accent">合成教学案例 · 非真实性能</strong><p className="mt-1">{profile.demo==='straggler'?'Rank 3 的 Expert GEMM 比其他 rank 多 80 µs；其他 rank 的通信任务更长，同时存在 Notify Wait。播放观察，随后在通信配对区核对证据。':'四个 rank 的真实计算相同，但 Rank 3 的记录时钟多了 300 µs。起点归零只能比较形态；已知偏移校正后，通信入口应一致。不要把时钟偏移当成慢卡。'}</p>{profile.demo==='clock'&&draft&&<button className="button-secondary mt-3" onClick={()=>{const next={...draft,mode:'clock' as const,clockConfirmed:true,workloadConfirmed:true,pairingConfirmed:true,uncertainty:'1',ranks:draft.ranks.map((r,i)=>({...r,offset:i===3?'-300':'0',eventId:'2'}))};setDraft(next);profile.analyze(next)}}>应用案例已知校时偏移（Rank 3 −300 µs）</button>}</section>}
    {draft&&<details className={`${panel} mt-4`} open={!result&&!profile.busy}>
      <summary className="cursor-pointer text-sm font-medium text-ink">校时、Rank 映射与观察范围 · {profile.info.length} 个执行域{dirty?' · 有未应用修改':''}</summary>
      <div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-xs text-muted">时间轴模式<select aria-label="多 rank 时间轴模式" className={control} value={draft.mode} onChange={e=>update({mode:e.target.value as RankConfig['mode'],clockConfirmed:false,pairingConfirmed:false,window:{from:'',to:''}})}><option value="relative">各自起点归零 · 仅形态对照</option><option value="clock">共享时钟 / 已知校时偏移</option></select></label><label className="text-xs text-muted">单 rank 最大校时误差（µs）<input className={control} aria-label="最大校时误差" type="number" min="0" step="any" value={draft.uncertainty} onChange={e=>update({uncertainty:e.target.value})} placeholder="未知则留空，不按 0 处理"/></label><div className="text-xs leading-6 text-muted">共同时间 = 原时间 + 校时偏移。正偏移向后移动；不得用“对齐通信入口”消除待分析的真实迟到。此版本只支持常数偏移，不校正时钟漂移。</div></div>
      <div className="mt-4 space-y-2 text-sm leading-6"><label className="flex items-start gap-2"><input className="mt-1.5" type="checkbox" disabled={draft.mode!=='clock'} checked={draft.clockConfirmed} onChange={e=>update({clockConfirmed:e.target.checked,pairingConfirmed:false})}/>我已依据采集工具或同步记录确认共享时钟／校时偏移在此窗口有效</label><label className="flex items-start gap-2"><input className="mt-1.5" type="checkbox" checked={draft.workloadConfirmed} onChange={e=>update({workloadConfirmed:e.target.checked,pairingConfirmed:false})}/>我已核对同一轮次、阶段、工作负载，以及参与 rank 范围</label></div>
      <p className="mt-3 text-xs leading-6 text-muted">默认 Rank 编号只是本次导入的展示编号，不从文件路径推断生产 rank。请按采样记录核对；同号 Device ID 在不同文件中仍是独立执行域。排除 rank 后，结论仅适用于所选子集。</p>
      <div className="mt-3 grid gap-3 md:grid-cols-2">{draft.ranks.map(r=>{const info=profile.info.find(i=>i.id===r.id)!;return <details className="min-w-0 rounded-xl border border-line p-3" key={r.id}><summary className="cursor-pointer text-xs text-ink">Rank {r.label} · 采样 {info.sourceIndex+1} · {info.count} 条 · {r.included?'纳入':'排除'}</summary><p className="mt-2 break-all text-xs text-muted">原执行域：{info.device}</p><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs text-muted">展示 Rank 编号<input className={control} aria-label={`${r.id} Rank 编号`} value={r.label} onChange={e=>rankEdit(r.id,{label:e.target.value})}/></label><label className="text-xs text-muted">校时偏移 µs<input className={control} aria-label={`${r.id} 校时偏移`} disabled={draft.mode!=='clock'} type="number" step="any" value={r.offset} onChange={e=>rankEdit(r.id,{offset:e.target.value})}/></label><label className="text-xs text-muted">Step（精确 ID）<input className={control} aria-label={`${r.id} Step`} value={r.step} onChange={e=>rankEdit(r.id,{step:e.target.value,eventId:''})} placeholder="空值纳入全部"/></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={r.included} onChange={e=>rankEdit(r.id,{included:e.target.checked})}/>纳入分析</label></div><p className="mt-2 break-words text-xs text-muted">Step 示例：{info.steps.slice(0,15).join('、')||'未标注'}{info.steps.length>15?` … 共 ${info.steps.length} 个`:''}。缺少时间戳 {info.missing} 条；源文件跳过 {info.skipped} 条。</p></details>})}</div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2">{(['from','to'] as const).map((k,i)=><label key={k} className="text-xs text-muted">相对完整图起点的窗口{i?'终点':'起点'}（µs）<input aria-label={`联合窗口${k}`} className={control} type="number" min="0" step="any" value={draft.window[k]} onChange={e=>update({window:{...draft.window,[k]:e.target.value},pairingConfirmed:false})} placeholder={i?'留空至末尾':'留空从开始'}/></label>)}</div><p className="mt-2 text-xs text-muted">窗口统计裁切跨边界任务的区间；调用数按相交任务计，不等同于完整调用耗时。清空边界恢复全范围。</p>
      <button className="button-primary mt-4" disabled={profile.busy} onClick={apply}>应用校时与范围</button>
    </details>}
    {result&&draft&&<>
      <div className="mt-5"><MultiRankTimeline result={result} active={active} disabled={dirty}/></div>
      <section className={`${panel} mt-5`} aria-label="通信实例配对">
        <p className="text-xs uppercase tracking-widest text-accent">Evidence / 02</p><h2 className="mt-2 text-xl font-medium text-ink">从“通信很长”到可核对的线索</h2><p className="mt-3 text-sm leading-6 text-muted">选择各 rank 的同一通信实例：同组、同轮次、相同粒度。设备任务的起点不一定是整个 collective 的入口；名称相同不足以证明匹配，也不能将 Notify 自动关联到远端 rank。</p>
        <details className="mt-4"><summary className="cursor-pointer py-2 text-sm text-accent">选择 / 更换每个 rank 的通信事件</summary><div className="mt-3 grid gap-3 md:grid-cols-2">{result.rows.map(row=><EventPicker key={row.id} row={row} value={draft.ranks.find(r=>r.id===row.id)!.eventId} onChange={eventId=>rankEdit(row.id,{eventId})}/>)}</div><label className="mt-4 flex items-start gap-2 text-sm leading-6"><input className="mt-1.5" type="checkbox" checked={draft.pairingConfirmed} onChange={e=>update({pairingConfirmed:e.target.checked})}/>我已核对通信组、轮次、参与者及事件粒度；这些事件可以人工配对</label><button className="button-primary mt-3" disabled={profile.busy} onClick={apply}>分析所选通信实例</button></details>
        {!result.pairing.ready?<p role="status" className="mt-4 rounded-lg border border-line bg-field p-4 text-sm text-muted">{result.pairing.reason}</p>:<>
          <div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-line bg-field p-4"><p className="text-xs text-muted">配对设备事件起点差</p><p data-testid="rank-entry-spread" className="mt-2 text-3xl font-medium text-ink">{us(result.pairing.spread)}</p><p className="mt-2 text-xs leading-6 text-muted">最晚观察到：{result.rows.filter(r=>result.pairing.latest.includes(r.id)).map(r=>`Rank ${r.label}`).join('、')}。不是已证明的关键路径。</p></div><div className="rounded-xl border border-line bg-field p-4 text-sm leading-6"><p className="font-medium text-ink">{result.pairing.uncertainty===null?'校时误差未知':result.pairing.distinguishable?'起点差超过声明误差界限':'差异未超过声明误差界限'}</p><p className="mt-2 text-muted">{result.pairing.uncertainty===null?'可以观察时间差，但不能证明 rank 到达顺序可靠。':`每 rank ±${num(result.pairing.uncertainty)} µs，两 rank 差值最多 ±${num(2*result.pairing.uncertainty)} µs。这是用户声明的误差界限，不是统计置信区间。`}</p></div></div>
          <div className="mt-4 space-y-3">{result.pairing.arrivals.map(arrival=>{const row=result.rows.find(r=>r.id===arrival.id)!;return <details key={arrival.id} className="rounded-xl border border-line p-4"><summary className="cursor-pointer text-sm text-ink">Rank {row.label} · 比最晚起点早 {us(arrival.lead)} · 此前等待交集 {us(arrival.waitBeforeLast)}</summary><p className="mt-3 break-words text-xs leading-6 text-secondary">{row.selected!.name} · Stream {row.selected!.stream} · 起点 {us(arrival.at)} · 时长 {us(row.selected!.duration)}</p><p className="mt-2 text-xs leading-6 text-muted">“等待交集”只表示该 rank 等待记录与所选事件起点至最晚起点之间的交集，不证明这些 Notify 由另一 rank 触发。查看其上游计算、Host 调度、通信组与同步关联后再判断。</p><h3 className="mt-3 text-xs text-ink">附近计算候选（按结束时间倒序；不是已知依赖）</h3><ul className="mt-2 space-y-1 text-xs text-muted">{row.preceding.map(e=><li className="break-words" key={e.id}>{e.name} · Stream {e.stream} · {us(e.start)} → {us(e.start+e.duration)}</li>)}</ul>{!row.preceding.length&&<p className="mt-2 text-xs text-muted">当前采样未记录到附近计算。</p>}</details>})}</div>
        </>}
      </section>
      <section className={`${panel} mt-5`} aria-label="逐 rank 数值对照"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-medium text-ink">数值对照 · 同一观察口径</h2><button className="button-secondary" disabled={dirty||profile.busy} onClick={download}><Download size={15}/>导出匿名数值</button></div>
        {draft.workloadConfirmed&&result.rows.length>1&&<p className="mt-3 text-sm leading-6 text-secondary">计算覆盖最大与最小相差 {us(Math.max(...result.rows.map(r=>r.compute))-Math.min(...result.rows.map(r=>r.compute)))}；执行调用数 {Math.min(...result.rows.map(r=>r.calls))}–{Math.max(...result.rows.map(r=>r.calls))}。这是负载／实现差异的核查线索，不能单凭时长证明 token 或专家分配不均。</p>}
        <div role="region" aria-label="Rank 覆盖统计表" tabIndex={0} className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="border-b border-line text-muted"><tr>{['Rank','执行调用','累计工作量','计算覆盖','通信覆盖','等待覆盖','等待且无执行覆盖','无记录覆盖'].map(t=><th className="px-3 py-3 font-normal" key={t}>{t}</th>)}</tr></thead><tbody>{result.rows.map(r=><tr key={r.id} className="border-b border-line/60"><th className="px-3 py-3 font-medium text-ink">{r.label}</th>{[String(r.calls),us(r.work),us(r.compute),us(r.communication),us(r.wait),us(r.waitOutsideExecution),us(r.uncovered)].map((s,i)=><td className="whitespace-nowrap px-3 py-3 font-mono" key={i}>{s}</td>)}</tr>)}</tbody></table></div><p className="mt-3 text-xs leading-6 text-muted">累计工作量可大于窗口跨度。覆盖均为区间并集；“无记录覆盖”不是已证实的设备空闲。缺少采集、分类错误、不同工作负载都会影响比较；时长差不等同于 token 分配不均。</p>
        {exported&&<p role="status" className="mt-3 text-xs leading-6 text-emerald-200">已导出匿名编号与数值；不含文件路径、原 Rank 编号、事件名称、绝对时间、校时偏移。性能数值仍可能敏感，请按团队政策分享。</p>}
      </section>
      <details className={`${panel} mt-4`}><summary className="cursor-pointer text-sm text-ink">数据质量与证据边界（{result.warnings.length} 条）</summary><ul className="mt-3 list-disc space-y-2 pl-4 text-xs leading-6 text-muted">{result.warnings.map((w,i)=><li key={i}>{w}</li>)}<li>忽略 {profile.ignored} 个不支持或中间重复文件。DB、原始二进制和日志未读取。</li><li>当前不解析跨 rank 的完整依赖图，不自动恢复缺失的通信组、Notify 发送者或时钟同步信息。人工配对形成取证线索，不构成自动根因诊断。</li></ul></details>
    </>}
    {!profile.config&&!profile.busy&&<div className="mt-6 grid gap-4 sm:grid-cols-3">{[['01','确认范围','同次采样、同一阶段，先排除预热或不同请求。'],['02','校准时钟','跨机器时间必须有同步证据；未知时只比较形态。'],['03','追溯证据','配对通信实例，再检查到达差、等待与附近计算。']].map(([index,title,text])=><div key={index} className={panel}><span className="font-mono text-xs text-accent">{index}</span><h2 className="mt-3 text-base font-medium text-ink">{title}</h2><p className="mt-2 text-sm leading-6 text-muted">{text}</p></div>)}</div>}
    <details className={`${panel} mt-5`}><summary className="cursor-pointer text-sm text-ink">方法、隐私与参考</summary><div className="mt-3 space-y-3 text-xs leading-6 text-muted"><p>所有解析与计算在本地 Worker 完成，不上传，不写入浏览器持久存储或 URL。离开整个性能板块、刷新、清空或替换会销毁联合分析；性能板块内切换保留内存结果。</p><p>支持设备完整 X 事件和逐任务 CSV；不自动配对 B/E，也不将 Host API 的提交时间混入设备时间线。多文件缺失信息会显式提示，不宣称兼容所有 CANN 版本或替代完整集群分析工具。</p><p>仅支持常数时钟偏移。长窗口可能存在漂移，需缩短窗口或先用采集工具校时；不能用首个 collective 的入口对齐证明同步。</p><p>参考：<a className="text-accent underline" href="https://perfetto.dev/docs/concepts/clock-sync" target="_blank" rel="noreferrer">Perfetto 时钟同步</a> · <a className="text-accent underline" href="https://www.hiascend.com/doc_center/source/en/mindstudio/830/practicalcases/GeneralPerformanceIssue/toolsample6_008.html" target="_blank" rel="noreferrer">MindStudio 快慢卡与同步等待案例</a></p></div></details>
  </div>
}
