export const newsSources = [
  {
    name: 'DeepMind',
    country: 'United Kingdom',
    category: 'ai',
    url: 'https://deepmind.google/blog/rss.xml',
    weight: 9,
  },
  {
    name: 'NVIDIA AI',
    country: 'United States',
    category: 'ai',
    url: 'https://blogs.nvidia.com/feed/',
    weight: 8,
  },
  {
    name: 'TechCrunch AI',
    country: 'United States',
    category: 'ai',
    url: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    weight: 7,
  },
  {
    name: 'Ars Technica',
    country: 'United States',
    category: 'technology',
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    weight: 7,
  },
  {
    name: 'Apple Newsroom',
    country: 'United States',
    category: 'technology',
    url: 'https://www.apple.com/newsroom/rss-feed.rss',
    weight: 8,
  },
  {
    name: 'NASA',
    country: 'United States',
    category: 'technology',
    url: 'https://www.nasa.gov/news-release/feed/',
    weight: 9,
  },
  {
    name: 'European Central Bank',
    country: 'European Union',
    category: 'finance',
    url: 'https://www.ecb.europa.eu/rss/press.html',
    weight: 10,
  },
  {
    name: 'U.S. Federal Reserve',
    country: 'United States',
    category: 'finance',
    url: 'https://www.federalreserve.gov/feeds/press_all.xml',
    weight: 10,
  },
  {
    name: 'Bank of England',
    country: 'United Kingdom',
    category: 'finance',
    url: 'https://www.bankofengland.co.uk/rss/news',
    weight: 9,
  },
  {
    name: 'Bank of Japan',
    country: 'Japan',
    category: 'finance',
    url: 'https://www.boj.or.jp/en/rss/whatsnew.xml',
    weight: 9,
  },
  {
    name: 'Bank of Canada',
    country: 'Canada',
    category: 'finance',
    url: 'https://www.bankofcanada.ca/feed/?post_type=press-releases',
    weight: 9,
  },
  {
    name: 'Reserve Bank of Australia',
    country: 'Australia',
    category: 'finance',
    url: 'https://www.rba.gov.au/rss/rss-cb-media-releases.xml',
    weight: 9,
  },
  {
    name: 'Bank for International Settlements',
    country: 'International',
    category: 'finance',
    url: 'https://www.bis.org/doclist/all_pressrels.rss',
    weight: 9,
  },
  {
    name: 'UN News',
    country: 'International',
    category: 'world',
    url: 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
    weight: 9,
  },
  {
    name: 'France 24',
    country: 'France',
    category: 'world',
    url: 'https://www.france24.com/en/rss',
    weight: 8,
  },
  {
    name: 'NPR World',
    country: 'United States',
    category: 'world',
    url: 'https://feeds.npr.org/1004/rss.xml',
    weight: 7,
  },
  {
    name: 'Africanews',
    country: 'Pan-African',
    category: 'world',
    url: 'https://www.africanews.com/feed/rss',
    weight: 7,
  },
  {
    name: 'Buenos Aires Times',
    country: 'Argentina',
    category: 'world',
    url: 'https://www.batimes.com.ar/feed',
    weight: 7,
  },
]
