export const newsSources = [
  {
    name: 'DeepMind',
    country: 'United Kingdom',
    category: 'ai',
    type: 'research',
    url: 'https://deepmind.google/blog/rss.xml',
    weight: 9,
  },
  {
    name: 'NVIDIA AI',
    country: 'United States',
    category: 'ai',
    type: 'news',
    url: 'https://blogs.nvidia.com/feed/',
    weight: 8,
  },
  {
    name: 'TechCrunch AI',
    country: 'United States',
    category: 'ai',
    type: 'news',
    url: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    weight: 7,
  },
  {
    name: 'Ars Technica',
    country: 'United States',
    category: 'technology',
    type: 'news',
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    weight: 7,
  },
  {
    name: 'Apple Newsroom',
    country: 'United States',
    category: 'technology',
    type: 'release',
    url: 'https://www.apple.com/newsroom/rss-feed.rss',
    weight: 8,
  },
  {
    name: 'NASA',
    country: 'United States',
    category: 'technology',
    type: 'research',
    url: 'https://www.nasa.gov/news-release/feed/',
    weight: 9,
  },
  {
    name: 'European Central Bank',
    country: 'European Union',
    category: 'finance',
    type: 'institution',
    url: 'https://www.ecb.europa.eu/rss/press.html',
    weight: 10,
  },
  {
    name: 'U.S. Federal Reserve',
    country: 'United States',
    category: 'finance',
    type: 'institution',
    url: 'https://www.federalreserve.gov/feeds/press_all.xml',
    weight: 10,
  },
  {
    name: 'Bank of England',
    country: 'United Kingdom',
    category: 'finance',
    type: 'institution',
    url: 'https://www.bankofengland.co.uk/rss/news',
    weight: 9,
  },
  {
    name: 'Bank of Japan',
    country: 'Japan',
    category: 'finance',
    type: 'institution',
    url: 'https://www.boj.or.jp/en/rss/whatsnew.xml',
    weight: 9,
  },
  {
    name: 'Bank of Canada',
    country: 'Canada',
    category: 'finance',
    type: 'institution',
    url: 'https://www.bankofcanada.ca/feed/?post_type=press-releases',
    weight: 9,
  },
  {
    name: 'Reserve Bank of Australia',
    country: 'Australia',
    category: 'finance',
    type: 'institution',
    url: 'https://www.rba.gov.au/rss/rss-cb-media-releases.xml',
    weight: 9,
  },
  {
    name: 'Bank for International Settlements',
    country: 'International',
    category: 'finance',
    type: 'institution',
    url: 'https://www.bis.org/doclist/all_pressrels.rss',
    weight: 9,
  },
  {
    name: 'UN News',
    country: 'International',
    category: 'world',
    type: 'institution',
    url: 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
    weight: 9,
  },
  {
    name: 'France 24',
    country: 'France',
    category: 'world',
    type: 'news',
    url: 'https://www.france24.com/en/rss',
    weight: 8,
  },
  {
    name: 'NPR World',
    country: 'United States',
    category: 'world',
    type: 'news',
    url: 'https://feeds.npr.org/1004/rss.xml',
    weight: 7,
  },
  {
    name: 'Africanews',
    country: 'Pan-African',
    category: 'world',
    type: 'news',
    url: 'https://www.africanews.com/feed/rss',
    weight: 7,
  },
  {
    name: 'Buenos Aires Times',
    country: 'Argentina',
    category: 'world',
    type: 'news',
    url: 'https://www.batimes.com.ar/feed',
    weight: 7,
  },
  {
    name: 'Hugging Face Blog',
    country: 'International',
    category: 'ai',
    type: 'engineering',
    url: 'https://huggingface.co/blog/feed.xml',
    weight: 10,
  },
  {
    name: 'vLLM Blog',
    country: 'International',
    category: 'ai',
    type: 'engineering',
    url: 'https://vllm.ai/blog/rss.xml',
    weight: 10,
  },
  {
    name: 'Google Research',
    country: 'United States',
    category: 'ai',
    type: 'research',
    url: 'https://research.google/blog/rss/',
    weight: 10,
  },
  {
    name: 'SGLang Releases',
    country: 'International',
    category: 'ai',
    type: 'release',
    url: 'https://github.com/sgl-project/sglang/releases.atom',
    weight: 10,
  },
  {
    name: 'vLLM Releases',
    country: 'International',
    category: 'ai',
    type: 'release',
    url: 'https://github.com/vllm-project/vllm/releases.atom',
    weight: 10,
  },
  {
    name: 'FlashInfer Releases',
    country: 'International',
    category: 'ai',
    type: 'release',
    url: 'https://github.com/flashinfer-ai/flashinfer/releases.atom',
    weight: 9,
  },
  {
    name: 'FlashInfer Blog',
    country: 'International',
    category: 'ai',
    type: 'engineering',
    url: 'https://flashinfer.ai/feed.xml',
    weight: 10,
  },
  {
    name: 'arXiv Distributed Systems',
    country: 'International',
    category: 'ai',
    type: 'research',
    url: 'https://export.arxiv.org/api/query?search_query=cat:cs.DC&sortBy=submittedDate&sortOrder=descending&max_results=20',
    weight: 8,
    includeKeywords: [
      'llm', 'language model', 'inference', 'serving', 'gpu', 'npu', 'accelerator',
      'tensor core', 'collective communication', 'sparse attention', 'kv cache',
      'mixture of experts', 'machine learning system', 'ai workload', 'deep learning',
    ],
    matchScope: 'title',
  },
  {
    name: 'PyTorch Blog',
    country: 'International',
    category: 'technology',
    type: 'engineering',
    url: 'https://pytorch.org/feed/',
    weight: 10,
  },
  {
    name: 'NVIDIA Technical Blog',
    country: 'United States',
    category: 'technology',
    type: 'engineering',
    url: 'https://developer.nvidia.com/blog/feed/',
    weight: 10,
  },
  {
    name: 'AMD ROCm Blog',
    country: 'United States',
    category: 'technology',
    type: 'engineering',
    url: 'https://rocm.blogs.amd.com/blog/atom.xml',
    weight: 10,
  },
  {
    name: 'Cloudflare Engineering',
    country: 'United States',
    category: 'technology',
    type: 'engineering',
    url: 'https://blog.cloudflare.com/rss/',
    weight: 9,
  },
  {
    name: 'GitHub Engineering',
    country: 'United States',
    category: 'technology',
    type: 'engineering',
    url: 'https://github.blog/engineering/feed/',
    weight: 9,
  },
  {
    name: 'Transformers Releases',
    country: 'International',
    category: 'ai',
    type: 'release',
    url: 'https://github.com/huggingface/transformers/releases.atom',
    weight: 10,
  },
  {
    name: 'TensorRT-LLM Releases',
    country: 'United States',
    category: 'technology',
    type: 'release',
    url: 'https://github.com/NVIDIA/TensorRT-LLM/releases.atom',
    weight: 10,
  },
  {
    name: 'Triton Releases',
    country: 'International',
    category: 'technology',
    type: 'release',
    url: 'https://github.com/triton-lang/triton/releases.atom',
    weight: 9,
  },
]
